### ISSUE TITLE
Signature verification issue

### ISSUE THREAD

**Issue by jpblair** [docker-library/tomcat#10]
When trying to build my Dockerfile, I get this error.  It seemed to build fine as recently as a few days ago:

---

Step 19 : RUN curl -SL "$TOMCAT_TGZ_URL" -o tomcat.tar.gz       && curl -SL "$T&& rm tomcat.tar.gz*ar.gz --strip-components=1
 ---> Running in xxxxxxxx
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    908      0 --:--:-- --:--:-- --:--:--  1244
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   262  100   262    0     0    505      0 --:--:-- --:--:-- --:--:--   678

gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
INFO[0017] The command [/bin/sh -c curl -SL "$TOMCAT_TGZ_URL" -o tomcat.tar.gz && rm tomcat.tar.gz*] returned a non-zero code: 2 z.asc

**Comment by tianon** [comment]
That sounds like it might have failed to fetch some of the keys in the previous step.  If you have the image ID of the previous `gpg` step, you can try doing `docker rmi <image-id>` and building again, or just build with `--no-cache`.
