### ISSUE TITLE
Running behind proxy with SSL termination

### ISSUE THREAD

**Issue by petrdvorak** [docker-library/tomcat#107]
We are running the Tomcat server behind the proxy that terminates SSL. Proxy correctly adds `X-Forwarded-*` headers and our application that runs in the container (Java application built using Spring Boot) is able to understand these headers. However, there is not a Tomcat configuration of `RemoteIpValve` that would pass the headers through:

```xml
<Engine/>
<Valve className="org.apache.catalina.valves.RemoteIpValve"
         remoteIpHeader="x-forwarded-for"
         protocolHeader="x-forwarded-proto"
         protocolHeaderHttpsValue="https" />
</Engine>
```

Could you please add some documentation that covers this topic, or allow some customization of the image (maybe a version with `RemoteIpValve` in place, so that we can use image that is ready to run behind proxy)?

**Comment by petrdvorak** [comment]
As a current workaround, we have following step in our `Dockerfile`:

```sh
# Add valve for proxy with SSL termination
RUN sed -i 's/<\/Host>/<Valve className="org.apache.catalina.valves.RemoteIpValve" remoteIpHeader="X-Forwarded-For" protocolHeader="X-Forwarded-Proto"\/><\/Host>/' /usr/local/tomcat/conf/server.xml
```

**Comment by yosifkit** [comment]
We only document how to run the image to create a container and where the configuration files are located.  Any specific configuration example is currently outside the scope of the image. The `tomcat` image is strictly upstream provided config; if you need anything different, it is bring your own or edit it (as you do with`sed`).

**Comment by petrdvorak** [comment]
Thank you for the reply and you are right. It makes sense to keep the documentation well scoped. I will publish a blog post instead, so that people with the issue can find solution somewhere.

**Comment by mattdrees** [comment]
Here's a variant on Petr's directive:
```dockerfile
RUN sed -i 's|\
  </Host>|\
    <Valve className="org.apache.catalina.valves.RemoteIpValve" \
      remoteIpHeader="X-Forwarded-For" \
      protocolHeader="X-Forwarded-Proto"/>\
  </Host>|' \
  /usr/local/tomcat/conf/server.xml
```

Same thing, just formatted with multiple lines and vertical bars for the `s` command.
