### ISSUE TITLE
Unable to pull tomcat:8.5-jre8 for linux

### ISSUE THREAD

**Issue by albestia** [docker-library/tomcat#109]
Since last build we get the following response:

$ docker pull tomcat:8.5-jre8
8.5-jre8: Pulling from library/tomcat
no matching manifest for linux/amd64 in the manifest list entries

**Comment by engrasif** [comment]
Its happening with all images i believe, i have tried 5 images and getting same error as above...

**Comment by vkhramtsov** [comment]
Waiting for fix

**Comment by kassovix** [comment]
A workaround is to add the architecture prefix :
`docker pull amd64/tomcat:8.5-jre8`

**Comment by rbkpro** [comment]
Or you can use FROM tomcat:9.0.4-jre8

**Comment by vkhramtsov** [comment]
@rbkpro as for me, I have do use tomcat 8.5

**Comment by rbkpro** [comment]
@vkhramtsov then you can do like @kassovix  suggested

**Comment by mikevader** [comment]
Will this be fixed soon? Not sure if I should go for the workaround or just wait?

**Comment by tianon** [comment]
Yep, as noted above, this is https://github.com/docker-library/official-images/issues/3835 plus build failures.  I've kicked off the build again and will keep an eye on it to make sure it completes.  Pulling the architecture prefix (also as noted above) is the simplest/fastest workaround for anyone who needs this _right_ away, and pulling by digest (using Git history of https://github.com/docker-library/repo-info to find the necessary value) is a good longer-term solution if pulling with an explicit architecture prefix is a no-go.

**Comment by SvenDowideit** [comment]
in case you need reports @tianon, its still happening for linux/amd64 - https://hub.docker.com/r/onaci/tomcat-docker/builds/blcvaukya6kgmw6prvwv7un/

I'm presuming its all just going to take time to settle down :D

**Comment by tianon** [comment]
Yep, as noted in the linked issue, it'll settle over time.

The amd64 build server is exceptionally sad and slow today.
