### ISSUE TITLE
s390x tomcat docker container should use IBM JVM and not openJDK which is very slow on systemz

### ISSUE THREAD

**Issue by adisht** [docker-library/tomcat#110]
This is a major setback for us, please consider packaging it with IBM java: https://hub.docker.com/r/s390x/ibmjava/

**Comment by jvano** [comment]
Thanks for the suggestion, we will evaluate your request

**Comment by tianon** [comment]
I'm going to close this in favor of #134 (given that it's my understanding that OpenJ9 in AdoptOpenJDK is the future of IBM Java). :+1:
