### ISSUE TITLE
Wrong openjdk version (10) in tomcat:8.0

### ISSUE THREAD

**Issue by arnaudmm** [docker-library/tomcat#113]
Hello,

Something really weird today, I've noticed opendj-10 is installed inside tomcat:8.0 docker image pulled from hub.docker.com

opendjk-7 is supposed to be used:
https://github.com/docker-library/tomcat/blob/af4b04d13a880a81a73dc2936afdf44147144418/8.0/jre7/Dockerfile

But here is the live result:
 $ docker run -it tomcat:8.0 bash
root@1be97f8d5941:/usr/local/tomcat# dpkg -l|grep jdk
ii  openjdk-10-jdk:amd64          10~46-2                        amd64        OpenJDK Development Kit (JDK)
ii  openjdk-10-jdk-headless:amd64 10~46-2                        amd64        OpenJDK Development Kit (JDK) (headless)
ii  openjdk-10-jre:amd64          10~46-2                        amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-10-jre-headless:amd64 10~46-2                        amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

And from an old (good) build, I got:
root@xx:/usr/local/tomcat# dpkg -l|grep jdk
ii  openjdk-7-jre:amd64           7u151-2.6.11-2~deb8u1            amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-7-jre-headless:amd64  7u151-2.6.11-2~deb8u1            amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

was there any issue with the tomcat:8.0 build ?

**Comment by yosifkit** [comment]
Related to https://github.com/docker-library/openjdk/issues/180.

**Comment by tianon** [comment]
Just to update further, we found the source of the issue, and are re-doing builds as quickly as the server can get through them. :heart:

**Comment by tianon** [comment]
This has been resolved for a few days now. :+1: :smile:
