### ISSUE TITLE
Unable to build 8.5/jre8/Dockerfile

### ISSUE THREAD

**Issue by autherlj** [docker-library/tomcat#114]
coz of I need to change the CATALINA_HOME path for tomcat install, after changed rebuild hit below error!

E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c set -eux;               savedAptMark="$(apt-mark showmanual)";  apt-get update;                 apt-get install -y --no-install-recommends gnupg
 dirmngr;               export GNUPGHOME="$(mktemp -d)";        for key in $GPG_KEYS; do                gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; d
one;            apt-get install -y --no-install-recommends wget ca-certificates;                success=;       for url in $TOMCAT_TGZ_URLS; do                 if wget
-O tomcat.tar.gz "$url"; then                   success=1;                      break;          fi;     done;   [ -n "$success" ];              echo "$TOMCAT_SHA1 *tomc
at.tar.gz" | sha1sum -c -;              success=;       for url in $TOMCAT_ASC_URLS; do                 if wget -O tomcat.tar.gz.asc "$url"; then

**Comment by yosifkit** [comment]
Most likely there was a Java bump between the time that you copied the Dockerfile and when you built it.  So it was probably this line that failed:

https://github.com/docker-library/tomcat/blob/abef52206ba44c495a37a90a8de3ab6d40431f12/8.5/jre8/Dockerfile#L115-L121

Please use the latest version of the Dockerfile if you are going to build the image yourself.
