### ISSUE TITLE
tomcat:8.5-jre8 has incorrect java version for ARM

### ISSUE THREAD

**Issue by aleksey-suprun** [docker-library/tomcat#119]
I've tried to play with tomcat image on my raspberry pi and faced with a strange issue. Image with tomcat 8.5 has `jre7` instead of required `jre8`:
```
$ sudo sudo docker run -it --rm tomcat:8.5-jre8 bash
root@07cb09d77102:/usr/local/tomcat# java -version
java version "1.7.0_171"
OpenJDK Runtime Environment (IcedTea 2.6.13) (7u171-2.6.13-1~deb8u1)
OpenJDK Zero VM (build 24.171-b02, interpreted mode)
```
Nevertheless, the same image has correct JRE on my local workstation (mac):
```
$ docker run -it --rm tomcat:8.5-jre8 bash
root@b242abcf54dd:/usr/local/tomcat# java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

Meantime, `tomcat:8.0-jre8` has correct JRE on both environments.

**Comment by tianon** [comment]
So, it looks like on your Pi, you're hitting https://github.com/moby/moby/issues/34875, and thus getting `arm32v5/tomcat:8.5-jre8`, which I've confirmed does appear to be built wrong -- I've removed the offending image on the build server and kicked off a build (https://doi-janky.infosiftr.net/job/multiarch/job/arm32v5/job/tomcat/127/console), but it is `arm32v5` and thus emulates floating point, so is very slow, but once that finishes it should fix the issue.

If you're running Raspbian, I'd recommend using `tomcat:8.5-jre8-alpine` instead (which will be `arm32v6`, and be a lot more performant), or if you're on a Pi 2 and are running Debian or Ubuntu, going explicitly for `arm32v7/tomcat:8.5-jre8` (which will also be a lot more performant).
