### ISSUE TITLE
8.0.52-jre8 image is not able run in 8080 port

### ISSUE THREAD

**Issue by abcdef123ghi** [docker-library/tomcat#122]
my enviroment is Ubuntu 18.04 and docker 18.5,I tried
sudo docker run -it --rm  tomcat:8.0.52-jre8
it didn't work,the port 8080 didn't be occupied by other application,it didn't work until I ran at 8888 port
cuz I tried "netstat -ap | grep 8080" to list application which using 8080 port,it showed nothing ran in that port
sudo docker run -it --rm -p 8888:8080 tomcat:8.0.52-jre8
it works

**Comment by wglambert** [comment]
`-p host_port:container_port` will open the port on the host to forward to the container port. 

If you don't use the `-p` or uppercase `-P` flag then the containers aren't accessible outside of their network. I'm not sure what the issue you're encountering is.

If you wanted to see the port listening on the host you'd want to grep for 8888. And if you connect to that port it will forward to the container on port 8080

See also https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose

**Comment by abcdef123ghi** [comment]
thank you very much,it works!!!!
sudo docker run -it --rm -p 8080:8080 tomcat:8.0.52-jre8
I really apperciated
