### ISSUE TITLE
pull run tomcat:8 on centos 7.1, rm -r fail

### ISSUE THREAD

**Issue by wushifeng** [docker-library/tomcat#123]
#1 pul docker and run
docker pull tomcat:8

[@centos7 work]$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/tomcat    8                   2d084b11164d        28 hours ago        463 MB
@centos7 work]$ docker run -itd 2d bash
fd71f3419d1d680d71b40b80d626a714c7bfa81bba75e041ae9d469456ff2105

[@centos7 work]$ docker attach fd
root@fd71f3419d1d:/usr/local/tomcat# cd /usr/local/tomcat/webapps/examples/jsp
root@fd71f3419d1d:/usr/local/tomcat/webapps/examples/jsp# ls -l error
total 24
-rw-r-----. 1 root root 1287 Jun 20 19:53 er.html
-rw-r-----. 1 root root 1412 Jun 20 19:53 err.jsp
-rw-r-----. 1 root root 1569 Jun 20 19:53 err.jsp.html
-rw-r-----. 1 root root 1283 Jun 20 19:53 error.html
-rw-r-----. 1 root root  965 Jun 20 19:53 errorpge.jsp
-rw-r-----. 1 root root 1104 Jun 20 19:53 errorpge.jsp.html
**root@fd71f3419d1d:/usr/local/tomcat/webapps/examples/jsp# rm -r error/
rm: cannot remove 'error/': Directory not empty
root@fd71f3419d1d:/usr/local/tomcat/webapps/examples/jsp# ls -l error
ls: cannot access 'error/er.html': No such file or directory
ls: cannot access 'error/err.jsp': No such file or directory
ls: cannot access 'error/err.jsp.html': No such file or directory
ls: cannot access 'error/error.html': No such file or directory
ls: cannot access 'error/errorpge.jsp': No such file or directory
ls: cannot access 'error/errorpge.jsp.html': No such file or directory
total 0
?????????? ? ? ? ?            ? er.html
?????????? ? ? ? ?            ? err.jsp
?????????? ? ? ? ?            ? err.jsp.html
?????????? ? ? ? ?            ? error.html
?????????? ? ? ? ?            ? errorpge.jsp
?????????? ? ? ? ?            ? errorpge.jsp.html**

error is:  when into container, atfer rm -r directory, the directory can not be used

#2 system enviroment is below
[@centos7 work]$ uname -a
Linux centos7.1-dev 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[@centos7 work]$ docker -v
Docker version 1.13.1, build 94f4240/1.13.1
[@centos7 work]$ cat /etc/docker/daemon.json 
{
"registry-mirrors": ["https://registry.docker-cn.com"] 
}

**Comment by wglambert** [comment]
On ubuntu, using `attach`
```console
$ docker pull tomcat:8
8: Pulling from library/tomcat
0bd44ff9c2cf: Already exists 
047670ddbd2a: Already exists 
ea7d5dc89438: Already exists 
4a05570971bb: Pull complete 
66f679cd5859: Pull complete 
89362eaac850: Pull complete 
d76c23323cb4: Pull complete 
f7a113d2d566: Pull complete 
f7ffd00be2be: Pull complete 
dd678d267c76: Pull complete 
70443378c06d: Pull complete 
a23e4449e436: Pull complete 
Digest: sha256:6210133c6a0c677aba36326dc152d1eb7e95fc7f77a628db507824505e626f0b
Status: Downloaded newer image for tomcat:8
$ docker run -itd 2d bash
c9ee099512bfecb999d12743d38f856ec06b74daed5de4ad5ce330faccf193f2
$ docker attach c9
root@c9ee099512bf:/usr/local/tomcat# cd /usr/local/tomcat/webapps/examples/jsp
root@c9ee099512bf:/usr/local/tomcat/webapps/examples/jsp# ls -l error
total 24
-rw-r----- 1 root root 1287 Jun 20 19:53 er.html
-rw-r----- 1 root root 1412 Jun 20 19:53 err.jsp
-rw-r----- 1 root root 1569 Jun 20 19:53 err.jsp.html
-rw-r----- 1 root root 1283 Jun 20 19:53 error.html
-rw-r----- 1 root root  965 Jun 20 19:53 errorpge.jsp
-rw-r----- 1 root root 1104 Jun 20 19:53 errorpge.jsp.html
root@c9ee099512bf:/usr/local/tomcat/webapps/examples/jsp# rm -r error/
root@c9ee099512bf:/usr/local/tomcat/webapps/examples/jsp# ls -l error
ls: cannot access 'error': No such file or directory
```

>error is: when into container, atfer rm -r directory, the directory can not be used

This is the expected function of the recursive flag for `rm`. Your errors are just more verbose since you're using `attach` instead of `exec -it bash`

```console
$ docker run -itd 2d bash
2c4ce439a391f5f65271adb2a1524710a6ea6adb430661b839f935a72a490d48
$ docker exec -it 2c4c bash
root@2c4ce439a391:/usr/local/tomcat# cd /usr/local/tomcat/webapps/examples/jsp
root@2c4ce439a391:/usr/local/tomcat/webapps/examples/jsp# ls -l error
total 24
-rw-r----- 1 root root 1287 Jun 20 19:53 er.html
-rw-r----- 1 root root 1412 Jun 20 19:53 err.jsp
-rw-r----- 1 root root 1569 Jun 20 19:53 err.jsp.html
-rw-r----- 1 root root 1283 Jun 20 19:53 error.html
-rw-r----- 1 root root  965 Jun 20 19:53 errorpge.jsp
-rw-r----- 1 root root 1104 Jun 20 19:53 errorpge.jsp.html
root@2c4ce439a391:/usr/local/tomcat/webapps/examples/jsp# rm -r error/
root@2c4ce439a391:/usr/local/tomcat/webapps/examples/jsp# ls -l error
ls: cannot access 'error': No such file or directory
```

https://linux.die.net/man/1/rm
>-r, -R, --recursive
remove directories and their contents recursively

**Comment by wushifeng** [comment]
I replay this problem in new vm. Docker's attach or exec isnot the cause. below is the full process:

[csbit@cent1503 sys]$ docker pull tomcat:8
Trying to pull repository docker.io/library/tomcat ... 
8: Pulling from docker.io/library/tomcat
0bd44ff9c2cf: Pull complete 
047670ddbd2a: Pull complete 
ea7d5dc89438: Pull complete 
4a05570971bb: Pull complete 
66f679cd5859: Pull complete 
89362eaac850: Pull complete 
d76c23323cb4: Pull complete 
f7a113d2d566: Pull complete 
f7ffd00be2be: Pull complete 
dd678d267c76: Pull complete 
70443378c06d: Pull complete 
a23e4449e436: Pull complete 
Digest: sha256:6210133c6a0c677aba36326dc152d1eb7e95fc7f77a628db507824505e626f0b
Status: Downloaded newer image for docker.io/tomcat:8
[csbit@cent1503 sys]$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/tomcat    8                   2d084b11164d        3 days ago          463 MB
docker.io/busybox   latest              8c811b4aec35        6 weeks ago         1.15 MB
[csbit@cent1503 sys]$ docker run -itd 2d0 bash
512792f0e8ceea2463ad1e21d2cc8535dccdfdc0ee5c8745eeb82561651ce755
[csbit@cent1503 sys]$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
512792f0e8ce        2d0                 "bash"              4 seconds ago       Up 3 seconds        8080/tcp            sharp_varahamihira
[csbit@cent1503 sys]$ docker exec -it 51 bash
root@512792f0e8ce:/usr/local/tomcat# pwd
/usr/local/tomcat
root@512792f0e8ce:/usr/local/tomcat# cd webapps/
root@512792f0e8ce:/usr/local/tomcat/webapps# ls
root@512792f0e8ce:/usr/local/tomcat/webapps# ls docs -l
total 1380
-rw-r-----. 1 root root  19513 Jun 20 19:53 BUILDING.txt
-rw-r-----. 1 root root   7138 Jun 20 19:53 RELEASE-NOTES.txt
-rw-r-----. 1 root root  16246 Jun 20 19:53 RUNNING.txt
drwxr-x---. 2 root root     20 Jul  4 02:24 WEB-INF
-rw-r-----. 1 root root   9176 Jun 20 19:53 aio.html
drwxr-x---. 2 root root     23 Jul  4 02:24 api
drwxr-x---. 3 root root   4096 Jul  4 02:24 appdev
-rw-r-----. 1 root root  12825 Jun 20 19:53 apr.html
drwxr-x---. 4 root root   4096 Jul  4 02:24 architecture
-rw-r-----. 1 root root   7704 Jun 20 19:53 balancer-howto.html
-rw-r-----. 1 root root  15876 Jun 20 19:53 building.html
-rw-r-----. 1 root root  12116 Jun 20 19:53 cgi-howto.html
-rw-r-----. 1 root root 293765 Jun 20 19:53 changelog.html
-rw-r-----. 1 root root  18825 Jun 20 19:53 class-loader-howto.html
-rw-r-----. 1 root root  43695 Jun 20 19:53 cluster-howto.html
-rw-r-----. 1 root root  10243 Jun 20 19:53 comments.html
drwxr-x---. 2 root root   4096 Jul  4 02:24 config
-rw-r-----. 1 root root   8784 Jun 20 19:53 connectors.html
-rw-r-----. 1 root root  18369 Jun 20 19:53 default-servlet.html
-rw-r-----. 1 root root  22751 Jun 20 19:53 deployer-howto.html
-rw-r-----. 1 root root   8708 Jun 20 19:53 developers.html
drwxr-x---. 2 root root     23 Jul  4 02:24 elapi
-rw-r-----. 1 root root  10513 Jun 20 19:53 extras.html
drwxr-x---. 2 root root   4096 Jul  4 02:24 funcspecs
-rw-r-----. 1 root root  16494 Jun 20 19:53 host-manager-howto.html
-rw-r-----. 1 root root  14314 Jun 20 19:53 html-host-manager-howto.html
-rw-r-----. 1 root root  30200 Jun 20 19:53 html-manager-howto.html
drwxr-x---. 3 root root   4096 Jul  4 02:24 images
-rw-r-----. 1 root root  17132 Jun 20 19:53 index.html
-rw-r-----. 1 root root  11921 Jun 20 19:53 introduction.html
-rw-r-----. 1 root root  23778 Jun 20 19:53 jasper-howto.html
-rw-r-----. 1 root root  66835 Jun 20 19:53 jdbc-pool.html
-rw-r-----. 1 root root  35231 Jun 20 19:53 jndi-datasource-examples-howto.html
-rw-r-----. 1 root root  53674 Jun 20 19:53 jndi-resources-howto.html
drwxr-x---. 2 root root     23 Jul  4 02:24 jspapi
-rw-r-----. 1 root root  24846 Jun 20 19:53 logging.html
-rw-r-----. 1 root root  74773 Jun 20 19:53 manager-howto.html
-rw-r-----. 1 root root   8227 Jun 20 19:53 maven-jars.html
-rw-r-----. 1 root root   8509 Jun 20 19:53 mbeans-descriptors-howto.html
-rw-r-----. 1 root root  10204 Jun 20 19:53 mbeans-descriptors.dtd
-rw-r-----. 1 root root  39158 Jun 20 19:53 monitoring.html
-rw-r-----. 1 root root  13282 Jun 20 19:53 proxy-howto.html
-rw-r-----. 1 root root  63208 Jun 20 19:53 realm-howto.html
-rw-r-----. 1 root root  35239 Jun 20 19:53 rewrite.html
-rw-r-----. 1 root root  35595 Jun 20 19:53 security-howto.html
-rw-r-----. 1 root root  30447 Jun 20 19:53 security-manager-howto.html
drwxr-x---. 2 root root     23 Jul  4 02:24 servletapi
-rw-r-----. 1 root root  14462 Jun 20 19:53 setup.html
-rw-r-----. 1 root root  17484 Jun 20 19:53 ssi-howto.html
-rw-r-----. 1 root root  41141 Jun 20 19:53 ssl-howto.html
drwxr-x---. 2 root root   4096 Jul  4 02:24 tribes
-rw-r-----. 1 root root  11534 Jun 20 19:53 virtual-hosting-howto.html
-rw-r-----. 1 root root  12594 Jun 20 19:53 web-socket-howto.html
drwxr-x---. 2 root root     23 Jul  4 02:24 websocketapi
-rw-r-----. 1 root root  22500 Jun 20 19:53 windows-auth-howto.html
-rw-r-----. 1 root root  23089 Jun 20 19:53 windows-service-howto.html
root@512792f0e8ce:/usr/local/tomcat/webapps# rm -rf docs
rm: cannot remove 'docs/WEB-INF': Directory not empty
rm: cannot remove 'docs/api': Directory not empty
rm: cannot remove 'docs/appdev/sample/docs': Directory not empty
rm: cannot remove 'docs/appdev/sample/src/mypackage': Directory not empty
rm: cannot remove 'docs/appdev/sample/web/WEB-INF': Directory not empty
rm: cannot remove 'docs/appdev/sample/web/images': Directory not empty
rm: cannot remove 'docs/architecture/requestProcess': Directory not empty
rm: cannot remove 'docs/architecture/startup': Directory not empty
rm: cannot remove 'docs/config': Directory not empty
rm: cannot remove 'docs/elapi': Directory not empty
rm: cannot remove 'docs/funcspecs': Directory not empty
rm: cannot remove 'docs/images/fonts': Directory not empty
rm: cannot remove 'docs/jspapi': Directory not empty
rm: cannot remove 'docs/servletapi': Directory not empty
rm: cannot remove 'docs/tribes': Directory not empty
rm: cannot remove 'docs/websocketapi': Directory not empty
root@512792f0e8ce:/usr/local/tomcat/webapps# ls -l docs
ls: cannot access 'docs/BUILDING.txt': No such file or directory
ls: cannot access 'docs/RELEASE-NOTES.txt': No such file or directory
ls: cannot access 'docs/RUNNING.txt': No such file or directory
ls: cannot access 'docs/aio.html': No such file or directory
ls: cannot access 'docs/apr.html': No such file or directory
ls: cannot access 'docs/balancer-howto.html': No such file or directory
ls: cannot access 'docs/building.html': No such file or directory
ls: cannot access 'docs/cgi-howto.html': No such file or directory
ls: cannot access 'docs/changelog.html': No such file or directory
ls: cannot access 'docs/class-loader-howto.html': No such file or directory
ls: cannot access 'docs/cluster-howto.html': No such file or directory
ls: cannot access 'docs/comments.html': No such file or directory
ls: cannot access 'docs/connectors.html': No such file or directory
ls: cannot access 'docs/default-servlet.html': No such file or directory
ls: cannot access 'docs/deployer-howto.html': No such file or directory
ls: cannot access 'docs/developers.html': No such file or directory
ls: cannot access 'docs/extras.html': No such file or directory
ls: cannot access 'docs/host-manager-howto.html': No such file or directory
ls: cannot access 'docs/html-host-manager-howto.html': No such file or directory
ls: cannot access 'docs/html-manager-howto.html': No such file or directory
ls: cannot access 'docs/index.html': No such file or directory
ls: cannot access 'docs/introduction.html': No such file or directory
ls: cannot access 'docs/jasper-howto.html': No such file or directory
ls: cannot access 'docs/jdbc-pool.html': No such file or directory
ls: cannot access 'docs/jndi-datasource-examples-howto.html': No such file or directory
ls: cannot access 'docs/jndi-resources-howto.html': No such file or directory
ls: cannot access 'docs/logging.html': No such file or directory
ls: cannot access 'docs/manager-howto.html': No such file or directory
ls: cannot access 'docs/maven-jars.html': No such file or directory
ls: cannot access 'docs/mbeans-descriptors-howto.html': No such file or directory
ls: cannot access 'docs/mbeans-descriptors.dtd': No such file or directory
ls: cannot access 'docs/monitoring.html': No such file or directory
ls: cannot access 'docs/proxy-howto.html': No such file or directory
ls: cannot access 'docs/realm-howto.html': No such file or directory
ls: cannot access 'docs/rewrite.html': No such file or directory
ls: cannot access 'docs/security-howto.html': No such file or directory
ls: cannot access 'docs/security-manager-howto.html': No such file or directory
ls: cannot access 'docs/setup.html': No such file or directory
ls: cannot access 'docs/ssi-howto.html': No such file or directory
ls: cannot access 'docs/ssl-howto.html': No such file or directory
ls: cannot access 'docs/virtual-hosting-howto.html': No such file or directory
ls: cannot access 'docs/web-socket-howto.html': No such file or directory
ls: cannot access 'docs/windows-auth-howto.html': No such file or directory
ls: cannot access 'docs/windows-service-howto.html': No such file or directory
total 24
??????????? ? ?    ?       ?            ? BUILDING.txt
??????????? ? ?    ?       ?            ? RELEASE-NOTES.txt
??????????? ? ?    ?       ?            ? RUNNING.txt
drwxr-x---. 1 root root   20 Jul  7 07:23 WEB-INF
??????????? ? ?    ?       ?            ? aio.html
drwxr-x---. 1 root root   23 Jul  7 07:23 api
drwxr-x---. 1 root root 4096 Jul  7 07:23 appdev
??????????? ? ?    ?       ?            ? apr.html
drwxr-x---. 1 root root 4096 Jul  7 07:23 architecture
??????????? ? ?    ?       ?            ? balancer-howto.html
??????????? ? ?    ?       ?            ? building.html
??????????? ? ?    ?       ?            ? cgi-howto.html
??????????? ? ?    ?       ?            ? changelog.html
??????????? ? ?    ?       ?            ? class-loader-howto.html
??????????? ? ?    ?       ?            ? cluster-howto.html
??????????? ? ?    ?       ?            ? comments.html
drwxr-x---. 1 root root 4096 Jul  7 07:23 config
??????????? ? ?    ?       ?            ? connectors.html
??????????? ? ?    ?       ?            ? default-servlet.html
??????????? ? ?    ?       ?            ? deployer-howto.html
??????????? ? ?    ?       ?            ? developers.html
drwxr-x---. 1 root root   23 Jul  7 07:23 elapi
??????????? ? ?    ?       ?            ? extras.html
drwxr-x---. 1 root root 4096 Jul  7 07:23 funcspecs
??????????? ? ?    ?       ?            ? host-manager-howto.html
??????????? ? ?    ?       ?            ? html-host-manager-howto.html
??????????? ? ?    ?       ?            ? html-manager-howto.html
drwxr-x---. 1 root root 4096 Jul  7 07:23 images
??????????? ? ?    ?       ?            ? index.html
??????????? ? ?    ?       ?            ? introduction.html
??????????? ? ?    ?       ?            ? jasper-howto.html
??????????? ? ?    ?       ?            ? jdbc-pool.html
??????????? ? ?    ?       ?            ? jndi-datasource-examples-howto.html
??????????? ? ?    ?       ?            ? jndi-resources-howto.html
drwxr-x---. 1 root root   23 Jul  7 07:23 jspapi
??????????? ? ?    ?       ?            ? logging.html
??????????? ? ?    ?       ?            ? manager-howto.html
??????????? ? ?    ?       ?            ? maven-jars.html
??????????? ? ?    ?       ?            ? mbeans-descriptors-howto.html
??????????? ? ?    ?       ?            ? mbeans-descriptors.dtd
??????????? ? ?    ?       ?            ? monitoring.html
??????????? ? ?    ?       ?            ? proxy-howto.html
??????????? ? ?    ?       ?            ? realm-howto.html
??????????? ? ?    ?       ?            ? rewrite.html
??????????? ? ?    ?       ?            ? security-howto.html
??????????? ? ?    ?       ?            ? security-manager-howto.html
drwxr-x---. 1 root root   23 Jul  7 07:23 servletapi
??????????? ? ?    ?       ?            ? setup.html
??????????? ? ?    ?       ?            ? ssi-howto.html
??????????? ? ?    ?       ?            ? ssl-howto.html
drwxr-x---. 1 root root 4096 Jul  7 07:23 tribes
??????????? ? ?    ?       ?            ? virtual-hosting-howto.html
??????????? ? ?    ?       ?            ? web-socket-howto.html
drwxr-x---. 1 root root   23 Jul  7 07:23 websocketapi
??????????? ? ?    ?       ?            ? windows-auth-howto.html
??????????? ? ?    ?       ?            ? windows-service-howto.html

**Comment by wushifeng** [comment]
urgent problem is:
when file in this state: ??????????? ? ? ? ? ? BUILDING.txt
I can not delete it!!!

**Comment by yosifkit** [comment]
Looks to be https://github.com/moby/moby/issues/27214 (ie, is a bug in docker's device mapper on older versions of CentOS).  See issue for possible workarounds.
