### ISSUE TITLE
Please provide apline variant without bundled webapps

### ISSUE THREAD

**Issue by Hubbitus** [docker-library/tomcat#124]
Alpine image intended to be tiny and light.

For what it frequently use is just provide builds of application with software WARs in [similar way](https://stackoverflow.com/questions/45861951/how-to-remove-root-folder-from-a-docker-container-running-tomcat-base-image/45862361#45862361):
```Dockerfile
FROM tomcat:9-alpine

# Delete existing ROOT folder
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy to images tomcat path
COPY <our application>.war /usr/local/tomcat/webapps/
```

Fist it always require clear webapp folder, and second it may be on 5.5Mb less in size:
```
$ sudo docker run --rm tomcat:9-alpine ls /usr/local/tomcat/webapps/
ROOT
docs
examples
host-manager
manager
$ sudo docker run --rm tomcat:9-alpine du -hs /usr/local/tomcat/webapps/
5.5M    /usr/local/tomcat/webapps/
```

If you wish it may be separate tag like f.e. `9-alpine-empty`.

**Comment by Hubbitus** [comment]
Is it worth try to make PR for that? Do you have contribution guide?

**Comment by tianon** [comment]
All our images are intended to be accurate representations of
upstream's recommended deployment, and in that light, I can't find any
documentation that suggests the example webapps should not be
included?  Perhaps you've got a better idea where to look?

**Comment by verglor** [comment]
I believe it's just no brainer to remove docs and example apps since that's useless in production. It's understandable that it is included in installation for developers to use but it is so obvious that it should be omitted in deployment that I wouldn't expect such explicit instruction in docs.

**Comment by tianon** [comment]
Looking deeper at this, not all of the bundled webapps are necessarily just "example" applications (so I'd disagree that removing all of them is a "no brainer").  For example, the manager and admin webapps seem genuinely quite useful, and thus presumptuous for us to remove prematurely (especially when they're part of the official bundles upstream publishes).

Without explicit guidance/recommendation from upstream on this point, I'm afraid I'm not willing to make the judgement call on which webapps are appropriate for us to axe and which ones we should keep, and would instead prefer to err on the side of keeping everything that upstream's own release bundles include (which is the source of our image contents).

**Comment by chanseokoh** [comment]
I don't agree that the image should always contain everything in the upstream. Upstream sources of various projects inevitably have all sorts of things including src, examples, man pages, docs, dev tools, etc. some of which are not desired for different purposes. As an example (which may not be a good one although I think it speaks the general point), the openjdk images have `11`, `11-slim`, `11-jre`, and `11-jre-slim` that are tailored for different demands.

The biggest problem I see is that, the `webapps/ROOT` has a pure example app that has its own `WEB-INF/web.xml`. So, to have an exploded app at the root context, you always have do an extra step to delete all the files under `webapps/ROOT` including `WEB-INF/web.xml` (newer Servlet apps don't require `web.xml`), which may not be obvious for some users. I was certainly bitten by this.

**Comment by jozefizso** [comment]
All the docker images for tomcat should not bundle webapps. No other framework ships sample code with a docker image intended for production use.

**Comment by timothyclarke** [comment]
@tianon 
Per the original request can we just get an `-empty` variant of the tags without the additional bloat?
Then everyone is happy and we don't have to get into the discussion on if it's desired or not. People will be able to decide which they prefer at `docker pull` time

My personal leaning : 
While some may see the [manager](https://tomcat.apache.org/tomcat-8.0-doc/manager-howto.html) and admin apps useful, their function is not in line with how most people run docker containers.
For Docker people take a base image, add their extra's build, publish then run that. When they want to deploy new apps they will create a new image. If they want an additional app they will create a completely separate container with only that other app (aka microservices) 
The primary functionality of the admin app is to mange multiple deployments in a traditional infrastructure model. While it might be beneficial in environments with limited resources, it adds a significant overhead that I highly doubt is used beyond a hobbiest / testing environment.

**Comment by verglor** [comment]
Hi @tianon, if you are not willing to remove docs and example/manager apps would you please consider at least removing `/usr/local/tomcat/webapps/ROOT` directory containing only hello world page ?

With this directory present, this official image cannot be used directly without storing application in external volume to override it's content. If anyone wants self-contained containerized application he has to either use 3rd party image or maintain custom image that just delete this directory which is very annoying and unfortunate.

For example you cannot use this image in [jib](https://github.com/GoogleContainerTools/jib), which is even mentioned in their [docs](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#war-projects):
![](https://i.imgur.com/0X2kmJd.png)

**Comment by verglor** [comment]
Also requested [official Tomcat documentation](https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications) states the following:

> General
> Tomcat ships with a number of web applications that are enabled by default. Vulnerabilities have been discovered in these applications in the past. Applications that are not required should be removed so the system will not be at risk if another vulnerability is discovered.
> 
> ROOT
> The ROOT web application presents a very low security risk but it does include the version of Tomcat that is being used. The ROOT web application should normally be removed from a publicly accessible Tomcat instance, not for security reasons, but so that a more appropriate default page is shown to users.
> 
> Documentation
> The documentation web application presents a very low security risk but it does identify the version of Tomcat that is being used. It should normally be removed from a publicly accessible Tomcat instance.
> 
> Examples
> The examples web application should always be removed from any security sensitive installation. While the examples web application does not contain any known vulnerabilities, it is known to contain features (particularly the cookie examples that display the contents of all received and allow new cookies to be set) that may be used by an attacker in conjunction with a vulnerability in another application deployed on the Tomcat instance to obtain additional information that would otherwise be unavailable.
> 
> Manager
> The Manager application allows the remote deployment of web applications and is frequently targeted by attackers due to the widespread use of weak passwords and publicly accessible Tomcat instances with the Manager application enabled. The Manager application is not accessible by default as no users are configured with the necessary access. If the Manager application is enabled then guidance in the section Securing Management Applications section should be followed.
> 
> Host Manager
> The Host Manager application allows the creation and management of virtual hosts - including the enabling of the Manager application for a virtual host. The Host Manager application is not accessible by default as no users are configured with the necessary access. If the Host Manager application is enabled then guidance in the section Securing Management Applications section should be followed.

**Comment by tianon** [comment]
Nice, that doc is exactly the kind of source I was looking for! :+1: :heart:

I've opened https://github.com/docker-library/tomcat/pull/181 to include that change. :+1:
