### ISSUE TITLE
OpenJDK 11 support

### ISSUE THREAD

**Issue by wstrange** [docker-library/tomcat#131]
An OpenJDK 11 / Tomcat 8 / 9 build would be really nice...

**Comment by philippebn** [comment]
with alpine version ?

**Comment by yosifkit** [comment]
Looking into this today (hopefully a PR shortly). Unfortunately there won't be any Alpine versions for jdk 11, since we don't have those in openjdk yet (https://github.com/docker-library/openjdk/issues/211).

**Comment by p-bakker** [comment]
What about using the OpenJDK 11 Alpine builds from https://hub.docker.com/r/adoptopenjdk/openjdk11/tags/
