### ISSUE TITLE
AdoptOpenJDK variants?

### ISSUE THREAD

**Issue by jordandev** [docker-library/tomcat#134]
It would be great if there was a plan to have variants of the images using the AdoptOpenJDK builds. With Oracle ending support of Java 8 in January 2019 it is starting to look like these builds are the best option to stay on a free LTS version of Java 8 (and Java 11 LTS in the future)

**Comment by aggregat4** [comment]
What was the resolution here? This is quite important. Oracle OpenJDK 11 is out of support since this month.

**Comment by tianon** [comment]
As I've just noted over in https://github.com/docker-library/tomcat/issues/154, this would require official images of AdoptOpenJDK as a prerequisite (https://github.com/docker-library/official-images/pull/5710).

**Comment by aggregat4** [comment]
Thank you for taking the time to reply and reference that issue!

Should we reopen this issue then? The AdoptOpenJDK Official Image issue seems well underway.

**Comment by tianon** [comment]
I'd rather reconsider this once that image becomes available.

**Comment by sarowar-cse** [comment]
It seems the PR(https://github.com/docker-library/official-images/pull/5710) is already merged and official images for AdoptOpenJDK is already available(https://hub.docker.com/_/adoptopenjdk).
I think we can reopen the issue and go forward with it.

**Comment by aggregat4** [comment]
@tianon shall we reopen this AdoptOpenJDK Support Issue or do you want to track this separately?

**Comment by tianon** [comment]
Nope, agreed, let's reopen this. :+1:

**Comment by tianon** [comment]
I think the main thing we need to figure out here (besides actually doing the integration work in the templates, etc which should be reasonably simple) is what the tag names are going to be.  Here's what we've got currently:

```console
$ bashbrew list https://github.com/docker-library/official-images/raw/master/library/tomcat
tomcat:7.0.94-jdk8
tomcat:7.0-jdk8
tomcat:7-jdk8
tomcat:7.0.94
tomcat:7.0
tomcat:7
tomcat:7.0.94-jdk8-slim
tomcat:7.0-jdk8-slim
tomcat:7-jdk8-slim
tomcat:7.0.94-slim
tomcat:7.0-slim
tomcat:7-slim
tomcat:8.5.41-jdk8
tomcat:8.5-jdk8
tomcat:8-jdk8
tomcat:jdk8
tomcat:8.5.41
tomcat:8.5
tomcat:8
tomcat:latest
tomcat:8.5.41-jdk8-slim
tomcat:8.5-jdk8-slim
tomcat:8-jdk8-slim
tomcat:jdk8-slim
tomcat:8.5.41-slim
tomcat:8.5-slim
tomcat:8-slim
tomcat:slim
tomcat:8.5.41-jdk11
tomcat:8.5-jdk11
tomcat:8-jdk11
tomcat:jdk11
tomcat:8.5.41-jdk11-slim
tomcat:8.5-jdk11-slim
tomcat:8-jdk11-slim
tomcat:jdk11-slim
tomcat:9.0.20-jdk8
tomcat:9.0-jdk8
tomcat:9-jdk8
tomcat:9.0.20-jdk8-slim
tomcat:9.0-jdk8-slim
tomcat:9-jdk8-slim
tomcat:9.0.20-jdk11
tomcat:9.0-jdk11
tomcat:9-jdk11
tomcat:9.0.20
tomcat:9.0
tomcat:9
tomcat:9.0.20-jdk11-slim
tomcat:9.0-jdk11-slim
tomcat:9-jdk11-slim
tomcat:9.0.20-slim
tomcat:9.0-slim
tomcat:9-slim
```

Hopefully we can figure out something clean that leaves the possibility of AdoptOpenJDK JRE variants open too.

**Comment by tianon** [comment]
Here's my proposal, which roughly matches what we used to have for Alpine (`tomcat:9-jdk11-alpine`):

```
tomcat:8.0-jdk11-adopt-hotspot
tomcat:8.0-jdk11-adopt-openj9
tomcat:8-jdk8-adopt-hotspot
```

etc.

@yosifkit thoughts?

**Comment by tianon** [comment]
(Since AdoptOpenJDK is the "distribution" of Java, where "jdk11" is the type/version.)

**Comment by vmassol** [comment]
+1 to have the official tomcat image use AdoptOpenKDK as its base image.  On the XWiki project, we need to continue supporting Java 8 and the Oracle JDK 8 has ended support already.

**Comment by tianon** [comment]
Alternative proposal:

```
tomcat:8.0-adoptjdk11-hotspot
tomcat:8.0-adoptjdk11-openj9
tomcat:8-adoptjdk8-hotspot
```

(I personally like this one a lot less than my previous suggestion.)

**Comment by sarowar-cse** [comment]
@tianon, first suggestion - $version-$jdk_version-$vendor-$vm (tomcat:8.0-jdk11-adopt-hotspot) looks better.
- New tags are consistent with existing ones
- Tag format is open to new vendors, new VMs.

But I'll suggest a minor change in the format, to $version-$jdk_version_$vm_$vendor, for example -
```
tomcat:8.0-jdk11-hotspot-adopt
tomcat:8.0-jdk11-openj9-adopt
tomcat:8-jdk8-hotspot-adopt
```
The only reason behind the suggestion is - it has a flow like - jdk based on different VMs and VMs can come from different vendors. It might help other vendors to keep their tags consistent with standard tags.

**Comment by tianon** [comment]
Are there any vendors that support multiple VM implementations besides AdoptOpenJDK?

**Comment by yosifkit** [comment]
I see that `tomcat:8.0-adoptjdk11-hotspot` would eventually lead to `tomcat:8.0-adoptjre11-hotspot` and that is not great. :disappointed:

I think all three styles, `adoptjdk11-hotspot`, `jdk11-adopt-hotspot`, and `jdk11-hotspot-adopt`, may not correctly represent the branding of "AdoptOpenJDK"; perhaps we don't add "adopt*" to the tag and just use `hotspot` and `openj9` as our differentiator in the tomcat repo? (with docs in the "Image Variants" section explaining that they are AdoptOpenJDK based)

```
tomcat:8.0-jdk11-hotspot
tomcat:8.0-jdk11-openj9
tomcat:8-jdk8-hotspot
tomcat:8-jre8-hotspot
```

Otherwise, I think we should use the full `adoptopenjdk` in the names to align with the name of the project. Choosing `tomcat:8.0-jdk11-hotspot-adoptopenjdk` or `tomcat:8.0-jdk11-adoptopenjdk-hotspot`, I prefer the vendor first.  If we do add more vendor options, it would be the vm that would most likely be left out of the name.

As far as I can tell, AdoptOpenJDK (i.e. IBM) is the only vendor offering openj9 See https://medium.com/@javachampions/java-is-still-free-2-0-0-6b9aa8d6d244 and https://www.eclipse.org/openj9/.
