### ISSUE TITLE
Tomcat9 on openjdk:10-jre-slim is failing to build due to missing openjdk-10-jdk package in sid

### ISSUE THREAD

**Issue by jivedude** [docker-library/tomcat#138]
Debian removed the openjdk-10-jdk package from Debian sid, so the apt-get install no longer pulls that version and consequently fails the build.

Debian removed on 12/5/2018 the openjdk10 packages from Debian sid, only the openjdk-10-jdk-headless versions are left.

[91m+ apt-get install -y --no-install-recommends dpkg-dev gcc libapr1-dev libssl-dev make openjdk-10-jdk=10.0.2+13-1

Reading package lists...

Building dependency tree...
Reading state information...

[91mE: Unable to locate package openjdk-10-jdk

**Comment by jivedude** [comment]
root@f4eca51115ad:/opt/tomcat# apt-cache search openjdk
jtreg - Regression Test Harness for the OpenJDK platform
openjdk-11-dbg - Java runtime based on OpenJDK (debugging symbols)
openjdk-11-demo - Java runtime based on OpenJDK (demos and examples)
openjdk-11-doc - OpenJDK Development Kit (JDK) documentation
openjdk-11-jdk - OpenJDK Development Kit (JDK)
openjdk-11-jdk-headless - OpenJDK Development Kit (JDK) (headless)
openjdk-11-jre - OpenJDK Java runtime, using Hotspot JIT
openjdk-11-jre-headless - OpenJDK Java runtime, using Hotspot JIT (headless)
openjdk-11-jre-zero - Alternative JVM for OpenJDK, using Zero
openjdk-11-source - OpenJDK Development Kit (JDK) source files
openjdk-12-dbg - Java runtime based on OpenJDK (debugging symbols)
openjdk-12-demo - Java runtime based on OpenJDK (demos and examples)
openjdk-12-doc - OpenJDK Development Kit (JDK) documentation
openjdk-12-jdk - OpenJDK Development Kit (JDK)
openjdk-12-jdk-headless - OpenJDK Development Kit (JDK) (headless)
openjdk-12-jre - OpenJDK Java runtime, using Hotspot JIT
openjdk-12-jre-headless - OpenJDK Java runtime, using Hotspot JIT (headless)
openjdk-12-jre-zero - Alternative JVM for OpenJDK, using Zero
openjdk-12-source - OpenJDK Development Kit (JDK) source files
openjdk-8-dbg - Java runtime based on OpenJDK (debugging symbols)
openjdk-8-demo - Java runtime based on OpenJDK (demos and examples)
openjdk-8-doc - OpenJDK Development Kit (JDK) documentation
openjdk-8-jdk - OpenJDK Development Kit (JDK)
openjdk-8-jdk-headless - OpenJDK Development Kit (JDK) (headless)
openjdk-8-jre - OpenJDK Java runtime, using Hotspot JIT
openjdk-8-jre-headless - OpenJDK Java runtime, using Hotspot JIT (headless)
openjdk-8-jre-zero - Alternative JVM for OpenJDK, using Zero/Shark
openjdk-8-source - OpenJDK Development Kit (JDK) source files
openjdk-8-jre-dcevm - Alternative VM for OpenJDK 8 with enhanced class redefinition
uwsgi-plugin-jvm-openjdk-11 - Java plugin for uWSGI (OpenJDK 11)
uwsgi-plugin-jwsgi-openjdk-11 - JWSGI plugin for uWSGI (OpenJDK 11)
uwsgi-plugin-ring-openjdk-11 - Closure/Ring plugin for uWSGI (OpenJDK 11)
uwsgi-plugin-servlet-openjdk-11 - JWSGI plugin for uWSGI (OpenJDK 11)
openjdk-10-jre-headless - OpenJDK Java runtime, using Hotspot JIT (headless)
openjdk-10-jdk-headless - OpenJDK Development Kit (JDK) (headless)

**Comment by tianon** [comment]
Yep, the `openjdk:10`-based variants will be removed soon; see https://github.com/docker-library/openjdk/pull/254.
