### ISSUE TITLE
please add support for multiple gpg servers

### ISSUE THREAD

**Issue by abmpicoli** [docker-library/tomcat#143]
Hi, everyone... 

First of all, *very neat idea* of having tomcat native being built within the image.

I'm trying to adapt the tomcat Dockerfile to using an IBM-provided jdk image, that uses ubuntu. 

And, so far so good... *except* for the fracking gpg keys:

I've seen issue #87  closed as no action, with the justification that "the gpg server should be stable"...

Well, the fact is that it isn't. And I don't think this is anything people  can control: zombie apocalypse, solar flares, a dog close to the server plug , an intern doing something silly, anything can cause a shortage, that breaks the build. I've tried 4 times the build using only the gpg server provided, and the build failed miserably all the times... I *had* to add the solution for cycling servers...

Maybe you should consider the same...

```
export GNUPGHOME="$(mktemp -d)"; \
	for key in $GPG_KEYS; do \
	for server in ha.pool.sks-keyservers.net \
	              hkp://p80.pool.sks-keyservers.net:80 \
	              keyserver.ubuntu.com \
	              hkp://keyserver.ubuntu.com:80 \
	              pgp.mit.edu; do \
								gpg --batch --keyserver "$server" --recv-keys "$key" && break || echo "Trying new server..." ; \
								done ;\
	done; \
```

**Comment by tianon** [comment]
See https://github.com/docker-library/tomcat/pull/127, which has pretty well eliminated this problem for us.
