### ISSUE TITLE
Provide Tomcat Native with openssl 1.1.1 for TLS1.3

### ISSUE THREAD

**Issue by logopk** [docker-library/tomcat#145]
Could you please update openssl in the image for TLS1.3?

Apparently the mechanism for updates from stretch in the former openjdk jessie debian are provided, now with the switch to stretch it should be adapted for openssl 1.1.1 from sid.

Thank you.

**Comment by tianon** [comment]
We can't pull OpenSSL from either Sid or Buster because libc has had an incompatible update. :disappointed:

**Comment by logopk** [comment]
Would you mind to tell me more about this? I’m trying on my own and can’t seem to get it to work without building openssl myself.

**Comment by tianon** [comment]
The AdoptOpenJDK variants added in #160 include OpenSSL 1.1.1 :tada: :+1:
