### ISSUE TITLE
Missing Permissions for temp folder

### ISSUE THREAD

**Issue by csk-bsi** [docker-library/tomcat#150]
Hello everyone,

Issue [Permission problem while running tomcat as a non-root user #35](https://github.com/docker-library/tomcat/issues/35) fixed the issue that the folder logs and work were read only for non root user:

` # fix permissions (especially for running as non-root)`
` # https://github.com/docker-library/tomcat/issues/35`
`	chmod -R +rX .; \`
`	chmod 777 logs work`

Unfortunately the folder temp is still missing. Which is required for some webapps.

**Comment by wglambert** [comment]
Which image are you using?

```console
$ docker run --user 1000:1000 -dit --rm --name tomcat tomcat:jre11-slim
19c48acf164b260192a01e7153a156e104ea5a214d25987f98912891b3e962b7

$ docker exec tomcat ls -l
total 152
-rw-r--r-- 1 root root  19539 Feb  5 11:45 BUILDING.txt
-rw-r--r-- 1 root root   6090 Feb  5 11:45 CONTRIBUTING.md
-rw-r--r-- 1 root root  57092 Feb  5 11:45 LICENSE
-rw-r--r-- 1 root root   1726 Feb  5 11:45 NOTICE
-rw-r--r-- 1 root root   3255 Feb  5 11:45 README.md
-rw-r--r-- 1 root root   7142 Feb  5 11:45 RELEASE-NOTES
-rw-r--r-- 1 root root  16262 Feb  5 11:45 RUNNING.txt
drwxr-xr-x 2 root root   4096 Mar  5 14:02 bin
drwxr-sr-x 2 root root   4096 Feb  5 11:45 conf
drwxr-sr-x 2 root staff  4096 Mar  5 14:02 include
drwxr-xr-x 2 root root   4096 Mar  5 13:59 lib
drwxrwxrwx 2 root root   4096 Mar 26 17:17 logs
drwxr-sr-x 3 root staff  4096 Mar  5 14:02 native-jni-lib
drwxr-xr-x 2 root root   4096 Mar  5 13:59 temp
drwxr-xr-x 7 root root   4096 Feb  5 11:44 webapps
drwxrwxrwx 3 root root   4096 Mar 26 17:17 work
```

**Comment by csk-bsi** [comment]
I use the same image.
The permissions for the temp folder are drwxr-xr-x instead of drwxrwxrwx  (work and logs folder). 
The image is used on an openshift cluster and therefore the write is not permitted into the temp folder ( a random user of the root group is used).

**Comment by p120ph37** [comment]
You should be able to pass `CATALINA_TMPDIR=/tmp` to the container to cause it to use that location instead of `/usr/local/tomcat/temp`.
