### ISSUE TITLE
Do we have any plans to make tomcat 9 with open JDK 11 alpine?

### ISSUE THREAD

**Issue by arvasrikanth** [docker-library/tomcat#156]
Right now tomcat 9 with jre8-alpine is available. Are there any plans to make tomcat9 image with open JDK -11 alpine. If not please post the the reasons

**Comment by wglambert** [comment]
There isn't an openjdk:11-alpine https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580

**Comment by wglambert** [comment]
Also a duplicate of https://github.com/docker-library/openjdk/issues/313 and https://github.com/docker-library/openjdk/issues/211#issuecomment-438173628

**Comment by DragD** [comment]
There is an openjdk11 for Alpine already:
https://pkgs.alpinelinux.org/packages?name=openjdk11&branch=edge
