### ISSUE TITLE
docker run tomcat successfully, but connection refused when visit

### ISSUE THREAD

**Issue by Crachman** [docker-library/tomcat#161]
when I run  `docker run -it --rm tomcat:8.0`, and start tomcat successfully.
but when visit http://localhost:8080 in the host, get error "connection refused"

but when I go into the container with `docker exec -it <container-id> bash` and run `wget http://localhost:8080`, it is ok.

I have tried to add port 8080 to public with firewall-cmd, but it's still not working.
this is my first time to use tomcat image, can you help?

my env: 
- run centos7 VM on macOS
- centos 7 kernel:4.19.9-1.el7
- docker 18.09.0

**Comment by wglambert** [comment]
You need to forward a port with [`-p 8080:8080`](https://docs.docker.com/config/containers/container-networking/#published-ports)

Without it you can still access the container from the host through its IP address
```console
$ docker run -d --rm tomcat:8.0
66626cb1caf85c06a76dc0509bff5a9caa971a30a41e92203a4fe722dd9cfc68

$ docker container inspect 666 | grep -i ipaddress
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAddress": "172.17.0.2",

$ curl 172.17.0.2:8080 -# | head
##########
#
#
#<!DOCTYPE html>
#<html lang="en">
#    <head>
#        <meta charset="UTF-8" />
#        <title>Apache Tomcat/8.0.53</title>
#        <link href="favicon.ico" rel="icon" type="image/x-icon" />
#        <link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />
##################################################### 100.0%
```
