### ISSUE TITLE
Amazon Corretto variant support

### ISSUE THREAD

**Issue by luiszimmermann** [docker-library/tomcat#162]
Is this possible? 

https://hub.docker.com/_/amazoncorretto
https://github.com/corretto/corretto-8-docker

**Comment by tianon** [comment]
Certainly not opposed (in fact quite like the idea, and it is part of why https://github.com/docker-library/tomcat/pull/160 was left intentionally somewhat generic).

I think the first hurdle is going to be that `amazoncorretto` is `yum`/`rpm`-based and our current template is entirely `apt-get`, so there's some definite adaptation work that would have to happen for this to move forward.

**Comment by tianon** [comment]
Took a first pass over in https://github.com/docker-library/tomcat/pull/163 :+1:
