### ISSUE TITLE
Are the Alpine-based images gone?

### ISSUE THREAD

**Issue by fabiendelpierre** [docker-library/tomcat#166]
It seems [this commit](https://github.com/docker-library/tomcat/commit/7eae995786f14b4e96010bcc11338724706e30eb) removed all the Alpine images, and that in turn broke some of our builds. If it matters, in particular we were using `8.5.xx-jre8-alpine`.

We're OK switching to the Debian-based "slim" builds as it's only a minor rework for us, but I was just wondering why Alpine was dropped. I dug around the issues/PRs a bit but couldn't find anything clear on that.

**Comment by wglambert** [comment]
Yeah Alpine is gone https://github.com/docker-library/tomcat/pull/158

https://github.com/docker-library/openjdk/pull/322
>Alpine/musl is not officially supported by the OpenJDK project, so this reflects that -- see "Project Portola" for the Alpine porting efforts which I understand are still in need of help

**Comment by fabiendelpierre** [comment]
Thanks for the clarification!
