### ISSUE TITLE
Missing APR library

### ISSUE THREAD

**Issue by jhmartin** [docker-library/tomcat#17]
tomcat:8.0 starts with
`26-Aug-2015 15:00:37.973 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib`

**Comment by md5** [comment]
There is another issue that already deals with installing native libraries to support optimal Tomcat performance and other features, though it deals more with `libtcnative` and not `libapr1`: https://github.com/docker-library/tomcat/issues/7

I think it would be best to consolidate the discussion there.

**Comment by jhmartin** [comment]
Closing in favor of #7
