### ISSUE TITLE
DNS Resolution not possible

### ISSUE THREAD

**Issue by Another1982** [docker-library/tomcat#171]
Maybe i made an mistake, but there us no lookup tool in the image and i think the nameresolution is not working at all. 
root@tomcat-test-646f4d67d4-nt88t:~# host anothermysql
-su: host: command not found
root@tomcat-test-646f4d67d4-nt88t:~# dig anothermysql
-su: dig: command not found
root@tomcat-test-646f4d67d4-nt88t:~# nslookup anothermysql
-su: nslookup: command not found
root@tomcat-test-646f4d67d4-nt88t:~# ping anothermysql
ping: anothermysql: Temporary failure in name resolution
root@tomcat-test-646f4d67d4-nt88t:~#

**Comment by yosifkit** [comment]
DNS resolution works fine:
```console
$ docker run -it --rm tomcat bash
root@40856b3372c9:/usr/local/tomcat# curl -I google.com
HTTP/1.1 301 Moved Permanently
Location: http://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Thu, 29 Aug 2019 20:33:37 GMT
Expires: Sat, 28 Sep 2019 20:33:37 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 219
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN

root@40856b3372c9:/usr/local/tomcat# 
```

Seeing that you are likely trying to hit another container named `anothermysql`, are they in the same `docker network` that is not the default `bridge` network?
