### ISSUE TITLE
Download of 7498c1055ea3 fails

### ISSUE THREAD

**Issue by bpieber** [docker-library/tomcat#172]
I am on Docker Desktop for Windows (19.03.1) and have problems downloading the official tomcat image. I tried several times yesterday and today but always get the following error:
a received unexpected HTTP status: 503 Service Unavailable

The download always fails at the layer 7498c1055ea3. Here is the console output:
```
$ docker pull tomcat:9-jdk8
9-jdk8: Pulling from library/tomcat
9cc2ad81d40d: Pulling fs layer
e6cb98e32a52: Pulling fs layer
ae1b8d879bad: Pulling fs layer
42cfa3699b05: Pulling fs layer
8d27062ef0ea: Pulling fs layer
9b91647396e3: Pulling fs layer
7498c1055ea3: Pulling fs layer
a183d8c2c929: Pulling fs layer
7340d476125e: Pulling fs layer
1d577c23bfea: Pulling fs layer
42cfa3699b05: Waiting
8d27062ef0ea: Waiting
9b91647396e3: Waiting
7498c1055ea3: Waiting
a183d8c2c929: Waiting
7340d476125e: Waiting
1d577c23bfea: Waiting
e6cb98e32a52: Verifying Checksum
e6cb98e32a52: Download complete
9cc2ad81d40d: Verifying Checksum
9cc2ad81d40d: Download complete
9cc2ad81d40d: Pull complete
e6cb98e32a52: Pull complete
ae1b8d879bad: Verifying Checksum
ae1b8d879bad: Download complete
ae1b8d879bad: Pull complete
9b91647396e3: Verifying Checksum
9b91647396e3: Download complete
8d27062ef0ea: Verifying Checksum
8d27062ef0ea: Download complete
a183d8c2c929: Verifying Checksum
a183d8c2c929: Download complete
42cfa3699b05: Verifying Checksum
42cfa3699b05: Download complete
42cfa3699b05: Pull complete
8d27062ef0ea: Pull complete
9b91647396e3: Pull complete
1d577c23bfea: Verifying Checksum
1d577c23bfea: Download complete
7340d476125e: Download complete
7498c1055ea3: Retrying in 5 seconds
7498c1055ea3: Retrying in 4 seconds
7498c1055ea3: Retrying in 3 seconds
7498c1055ea3: Retrying in 2 seconds
7498c1055ea3: Retrying in 1 second
7498c1055ea3: Downloading
7498c1055ea3: Retrying in 10 seconds
7498c1055ea3: Retrying in 9 seconds
7498c1055ea3: Retrying in 8 seconds
7498c1055ea3: Retrying in 7 seconds
7498c1055ea3: Retrying in 6 seconds
7498c1055ea3: Retrying in 5 seconds
7498c1055ea3: Retrying in 4 seconds
7498c1055ea3: Retrying in 3 seconds
7498c1055ea3: Retrying in 2 seconds
7498c1055ea3: Retrying in 1 second
7498c1055ea3: Retrying in 15 seconds
7498c1055ea3: Retrying in 14 seconds
7498c1055ea3: Retrying in 13 seconds
7498c1055ea3: Retrying in 12 seconds
7498c1055ea3: Retrying in 11 seconds
7498c1055ea3: Retrying in 10 seconds
7498c1055ea3: Retrying in 9 seconds
7498c1055ea3: Retrying in 8 seconds
7498c1055ea3: Retrying in 7 seconds
7498c1055ea3: Retrying in 6 seconds
7498c1055ea3: Retrying in 5 seconds
7498c1055ea3: Retrying in 4 seconds
7498c1055ea3: Retrying in 3 seconds
7498c1055ea3: Retrying in 2 seconds
7498c1055ea3: Retrying in 1 second
7498c1055ea3: Retrying in 20 seconds
7498c1055ea3: Retrying in 19 seconds
7498c1055ea3: Retrying in 18 seconds
7498c1055ea3: Retrying in 17 seconds
7498c1055ea3: Retrying in 16 seconds
7498c1055ea3: Retrying in 15 seconds
7498c1055ea3: Retrying in 14 seconds
7498c1055ea3: Retrying in 13 seconds
7498c1055ea3: Retrying in 12 seconds
7498c1055ea3: Retrying in 11 seconds
7498c1055ea3: Retrying in 10 seconds
7498c1055ea3: Retrying in 9 seconds
7498c1055ea3: Retrying in 8 seconds
7498c1055ea3: Retrying in 7 seconds
7498c1055ea3: Retrying in 6 seconds
7498c1055ea3: Retrying in 5 seconds
7498c1055ea3: Retrying in 4 seconds
7498c1055ea3: Retrying in 3 seconds
7498c1055ea3: Retrying in 2 seconds
7498c1055ea3: Retrying in 1 second
7498c1055ea3: Downloading
received unexpected HTTP status: 503 Service Unavailable
```
Does anyone have an idea how I can solve this or at least work around the problem?

Bernhard

**Comment by bpieber** [comment]
> 
> 
> I am on Docker Desktop for Windows (19.03.1) and have problems downloading the official tomcat image. I tried several times yesterday and today but always get the following error:
> a received unexpected HTTP status: 503 Service Unavailable
> 
> The download always fails at the layer 7498c1055ea3. Here is the console output:
> 
> ```
> $ docker pull tomcat:9-jdk8
> 9-jdk8: Pulling from library/tomcat
> 9cc2ad81d40d: Pulling fs layer
> e6cb98e32a52: Pulling fs layer
> ae1b8d879bad: Pulling fs layer
> 42cfa3699b05: Pulling fs layer
> 8d27062ef0ea: Pulling fs layer
> 9b91647396e3: Pulling fs layer
> 7498c1055ea3: Pulling fs layer
> a183d8c2c929: Pulling fs layer
> 7340d476125e: Pulling fs layer
> 1d577c23bfea: Pulling fs layer
> 42cfa3699b05: Waiting
> 8d27062ef0ea: Waiting
> 9b91647396e3: Waiting
> 7498c1055ea3: Waiting
> a183d8c2c929: Waiting
> 7340d476125e: Waiting
> 1d577c23bfea: Waiting
> e6cb98e32a52: Verifying Checksum
> e6cb98e32a52: Download complete
> 9cc2ad81d40d: Verifying Checksum
> 9cc2ad81d40d: Download complete
> 9cc2ad81d40d: Pull complete
> e6cb98e32a52: Pull complete
> ae1b8d879bad: Verifying Checksum
> ae1b8d879bad: Download complete
> ae1b8d879bad: Pull complete
> 9b91647396e3: Verifying Checksum
> 9b91647396e3: Download complete
> 8d27062ef0ea: Verifying Checksum
> 8d27062ef0ea: Download complete
> a183d8c2c929: Verifying Checksum
> a183d8c2c929: Download complete
> 42cfa3699b05: Verifying Checksum
> 42cfa3699b05: Download complete
> 42cfa3699b05: Pull complete
> 8d27062ef0ea: Pull complete
> 9b91647396e3: Pull complete
> 1d577c23bfea: Verifying Checksum
> 1d577c23bfea: Download complete
> 7340d476125e: Download complete
> 7498c1055ea3: Retrying in 5 seconds
> 7498c1055ea3: Retrying in 4 seconds
> 7498c1055ea3: Retrying in 3 seconds
> 7498c1055ea3: Retrying in 2 seconds
> 7498c1055ea3: Retrying in 1 second
> 7498c1055ea3: Downloading
> 7498c1055ea3: Retrying in 10 seconds
> 7498c1055ea3: Retrying in 9 seconds
> 7498c1055ea3: Retrying in 8 seconds
> 7498c1055ea3: Retrying in 7 seconds
> 7498c1055ea3: Retrying in 6 seconds
> 7498c1055ea3: Retrying in 5 seconds
> 7498c1055ea3: Retrying in 4 seconds
> 7498c1055ea3: Retrying in 3 seconds
> 7498c1055ea3: Retrying in 2 seconds
> 7498c1055ea3: Retrying in 1 second
> 7498c1055ea3: Retrying in 15 seconds
> 7498c1055ea3: Retrying in 14 seconds
> 7498c1055ea3: Retrying in 13 seconds
> 7498c1055ea3: Retrying in 12 seconds
> 7498c1055ea3: Retrying in 11 seconds
> 7498c1055ea3: Retrying in 10 seconds
> 7498c1055ea3: Retrying in 9 seconds
> 7498c1055ea3: Retrying in 8 seconds
> 7498c1055ea3: Retrying in 7 seconds
> 7498c1055ea3: Retrying in 6 seconds
> 7498c1055ea3: Retrying in 5 seconds
> 7498c1055ea3: Retrying in 4 seconds
> 7498c1055ea3: Retrying in 3 seconds
> 7498c1055ea3: Retrying in 2 seconds
> 7498c1055ea3: Retrying in 1 second
> 7498c1055ea3: Retrying in 20 seconds
> 7498c1055ea3: Retrying in 19 seconds
> 7498c1055ea3: Retrying in 18 seconds
> 7498c1055ea3: Retrying in 17 seconds
> 7498c1055ea3: Retrying in 16 seconds
> 7498c1055ea3: Retrying in 15 seconds
> 7498c1055ea3: Retrying in 14 seconds
> 7498c1055ea3: Retrying in 13 seconds
> 7498c1055ea3: Retrying in 12 seconds
> 7498c1055ea3: Retrying in 11 seconds
> 7498c1055ea3: Retrying in 10 seconds
> 7498c1055ea3: Retrying in 9 seconds
> 7498c1055ea3: Retrying in 8 seconds
> 7498c1055ea3: Retrying in 7 seconds
> 7498c1055ea3: Retrying in 6 seconds
> 7498c1055ea3: Retrying in 5 seconds
> 7498c1055ea3: Retrying in 4 seconds
> 7498c1055ea3: Retrying in 3 seconds
> 7498c1055ea3: Retrying in 2 seconds
> 7498c1055ea3: Retrying in 1 second
> 7498c1055ea3: Downloading
> received unexpected HTTP status: 503 Service Unavailable
> ```
> 
> Does anyone have an idea how I can solve this or at least work around the problem?
> 
>     * Bernhard

**Comment by wglambert** [comment]
`503 Service Unavailable`
Seems like a networking or Dockerhub issue

```console
$ docker pull tomcat:9-jdk8
9-jdk8: Pulling from library/tomcat
9cc2ad81d40d: Pull complete 
e6cb98e32a52: Pull complete 
ae1b8d879bad: Pull complete 
42cfa3699b05: Pull complete 
8d27062ef0ea: Pull complete 
9b91647396e3: Pull complete 
7498c1055ea3: Pull complete 
a183d8c2c929: Pull complete 
7340d476125e: Pull complete 
1d577c23bfea: Pull complete 
Digest: sha256:e3c3eaa120e9dc4fdfc471a85d770b039af54ff03d2288bfa115d99c491ae922
Status: Downloaded newer image for tomcat:9-jdk8
```

I didn't find any recent related issues on the hub-feedback https://github.com/docker/hub-feedback/issues
