### ISSUE TITLE
JRE Variants?

### ISSUE THREAD

**Issue by julienchastang** [docker-library/tomcat#175]
Pre-AdoptOpenJDK, there were JRE variants as part of this project. I now only see JDK variants available. Is there a reason for this change? I perused the GitHub issues for this project but did not find a reference for the loss of JRE options.

For example, I see `tomcat:8.5-jdk8` but no `tomcat:8.5-jre8`.

Edit:

To clarify `tomcat:8.5-jre8` exists, but it is no longer listed and is running an older version of Tomcat `8.5.47` versus `8.5.41` so it is presumably no longer maintained.

**Comment by wglambert** [comment]
https://github.com/docker-library/openjdk/pull/322
>I've personally looked at `tomcat`, and the practical implications there are going to be that we switch from being only JRE variants to being only JDK variants (since we need the JDK to compile Tomcat Native and it wasn't worth doing the legwork to make that work just for OpenJDK 8 JRE, and `jlink` doesn't work there because `tomcat` is intended to host arbitrary user code).

**Comment by julienchastang** [comment]
And also "no more OpenJDK 11 JRE images..." Excellent. Thank you. That is the reference I need.
