### ISSUE TITLE
minor version bump breaks Dockerfile, use archive.apache.org instead?

### ISSUE THREAD

**Issue by drocsid** [docker-library/tomcat#18]
Recently I was using this tomcat Dockerfile, and the current tomcat minor released was bumped from 7.0.63 to 7.0.64. This broke my Dockerfile.The Dockerfile could reference the tomcat archive for the version, so that version bumps don't break the dockerfile. It appears the current version is also available in the archive. Changing the url from www.apache.org to  archive.apache.org made my Dockerfile build-able again.

Should the Dockerfile use the archive instead?

```
 RUN set -x 	&& curl -fSL "$TOMCAT_TGZ_URL" -o tomcat.tar.gz 	&& curl -fSL "$TOMCAT_TGZ_URL.asc" -o tomcat.tar.gz.asc 	&& gpg --verify tomcat.tar.gz.asc 	&& tar -xvf tomcat.tar.gz --strip-components=1 	&& rm bin/*.bat 	&& rm tomcat.tar.gz*
 ---> Running in 8a748b3e0656
[91m+ curl -fSL https://www.apache.org/dist/tomcat/tomcat-7/v7.0.63/bin/apache-tomcat-7.0.63.tar.gz -o tomcat.tar.gz
[0m[91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 [0m[91m                                Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[0m[91m
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:[0m[91m--:--     0[0m[91m
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--[0m[91m     0[0m[91mcurl: (22) The requested URL returned error: 404 Not Found
[0mThe command '/bin/sh -c set -x 	&& curl -fSL "$TOMCAT_TGZ_URL" -o tomcat.tar.gz 	&& curl -fSL "$TOMCAT_TGZ_URL.asc" -o tomcat.tar.gz.asc 	&& gpg --verify tomcat.tar.gz.asc 	&& tar -xvf tomcat.tar.gz --strip-components=1 	&& rm bin/*.bat 	&& rm tomcat.tar.gz*' returned a non-zero code: 22
```

**Comment by tianon** [comment]
Any particular reason you're using the `Dockerfile` here directly instead of just using the image?  I do like archive.apache.org, but using it by default isn't what upstream recommends (I guess they don't have the same bandwidth available to it or something?) so I'm hesitant to switch and am more curious about what the use-case for building this instead of doing `FROM tomcat:x.y.z` is.
