### ISSUE TITLE
JRE is no longer supported?

### ISSUE THREAD

**Issue by fuminori-ido-m** [docker-library/tomcat#180]
I have used "tomcat:9-jre11-slim" image, however it looks no longer supported according to https://hub.docker.com/_/tomcat   ...Is this true?

commit:7eae995786f14b of this repository deletes all of X/jreY/Dockerfile in this repository.

**Comment by wglambert** [comment]
https://github.com/docker-library/openjdk/issues/319
>Our builds for OpenJDK 12 come from https://jdk.java.net/12/, and as you can see they're JDK only.

Openjdk 8 and 11 come from https://adoptopenjdk.net/upstream.html which does publish a JRE variant
https://github.com/docker-library/openjdk/issues/272

**Comment by wglambert** [comment]
I updated the reference issue we have at https://github.com/docker-library/openjdk/issues/272 with information on the JRE variants
