### ISSUE TITLE
Why move webapps to webapps.dist?

### ISSUE THREAD

**Issue by chenliu1993** [docker-library/tomcat#183]
tomcat cannot find the webapps.dist dir. The webpage cannot be accessed.
version 8.5.50

**Comment by bel-gacem** [comment]
just to avoid preinstalled apps (ROOT, manager...) to be loaded by default at container startup.
https://github.com/docker-library/tomcat/blob/807a2b4f219d70f5ba6f4773d4ee4ee155850b0d/8.5/jdk8/openjdk/Dockerfile#L64

**Comment by tianon** [comment]
Yep, see also https://github.com/docker-library/tomcat/pull/181 / https://github.com/docker-library/tomcat/issues/124 for additional detail.

**Comment by chenliu1993** [comment]
Got it! Thanks!
