### ISSUE TITLE
Rebuild Tomcat 7 JRE image 

### ISSUE THREAD

**Issue by rmkanda** [docker-library/tomcat#186]
The last published tomcat image with JRE 8 is 9 months old. Can we rebuild the image?

![image](https://user-images.githubusercontent.com/38713281/73767426-72d1a180-479d-11ea-856c-623c2d3530a5.png)

cc: @yosifkit @tianon

**Comment by wglambert** [comment]
There's no more JRE images https://github.com/docker-library/tomcat/pull/158
>all "jre" variants of the `tomcat` image are going away because we have to have the JDK to compile Tomcat Native and don't have an easy way to install that temporarily like we did with the Debian-package-based `openjdk:jre` images :disappointed:


https://github.com/docker-library/official-images/pull/5985

**Comment by rmkanda** [comment]
Thanks @wglambert for the updates. I will close the bug.
