### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by wxz0107** [docker-library/tomcat#199]
Caused by: java.lang.UnsatisfiedLinkError: /usr/local/openjdk-8/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

image:tomcat:8.5.54-jdk8-openjdk-slim

what causes this error?
how to solve ?

**Comment by wglambert** [comment]
The `slim` variant doesn't have `libfreetype6` https://github.com/docker-library/openjdk/issues/333#issuecomment-500620708

You can use the non-slim variant or make a derivative Dockerfile `FROM tomcat:8.5.54-jdk8-openjdk-slim` to install any additional packages

**Comment by wxz0107** [comment]
thanks
