### ISSUE TITLE
Latest Dockerfiles seem to have broken RewriteValve

### ISSUE THREAD

**Issue by manithree** [docker-library/tomcat#206]
I've been using the tomcat 8.5 dockers for some time, and started using the rewritevalve about a year ago to facilitate a migration.  It worked fine in 8.5.51, but when I upgraded to the latest 8.5.57, my rewrites stopped working.  The rewrite was getting applied (checking the access log, and my rewrite rules add a request parameter), but they always 404'ed.

Attached is a simple example, that I think reproduces the problem.  After building and running this docker, /examples works, and /placeholder gets rewritten to /examples, but 404s:

172.17.0.1 - - [07/Aug/2020:20:39:15 +0000] "GET /examples HTTP/1.1" 302 -
172.17.0.1 - - [07/Aug/2020:20:39:20 +0000] "GET /examples HTTP/1.1" 404 682

That's from the localhost_access log.  The first request was directly to /examples, the second to /placeholder.

[tc8test.zip](https://github.com/docker-library/tomcat/files/5043580/tc8test.zip)

I worked around this by modifying the old 8.5.51 Dockerfile to install 8.5.57.  My rewrites work in that image.

Also, it looks like my 8.5.51 Dockerfile was a modified version of about an 8.5.4x (pre-ddist) Dockerfile.  So, that's what I'm still using, modified more to work with 8.5.57.

ETA: One final thing I forgot to mention.  The configuration in the attached docker (server.xml and rewrite.config) works correctly if I just untar tomcat 8.5.57 and run that.  It only 404s in the docker.

**Comment by wglambert** [comment]
Looking through [the changes](https://githistory.xyz/docker-library/tomcat/blob/master/8.5/jdk8/adoptopenjdk-hotspot/Dockerfile) the only thing we've altered was present in the 8.5.50 and 8.5.51 images https://github.com/docker-library/tomcat/pull/181
https://github.com/docker-library/official-images/pull/7226

**Comment by manithree** [comment]
Found it.  The problem is webapps.dist.  The rewrites don't work if there's no ROOT  in webapps.  I added:
mv webapps.dist/ROOT webapps/
to the RUN in my Dockerfile, and now the rewrites work as expected (and as before).
