### ISSUE TITLE
Intermittent issue fetching keys

### ISSUE THREAD

**Issue by mettacrawler** [docker-library/tomcat#207]
I tried the same `docker build...` twice and it crashed trying to retrieve keys:
```
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 79F7026C690BAA50B92CD8B66A3AD3F4F22C4FED
gpg: requesting key F22C4FED from hkp server ha.pool.sks-keyservers.net
gpgkeys: key 79F7026C690BAA50B92CD8B66A3AD3F4F22C4FED can't be retrieved
```

I worked around it by modifying the code to try twice:

```
 	for key in $GPG_KEYS; do \
-		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" || gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
 	done; \
```
Then it built successfully for me.

Back in 2016 a similar gpg error happened in an automated build:
https://github.com/docker-library/official-images/pull/2445
(search that page for: can't be retrieved)

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749
