### ISSUE TITLE
how setting JAVA_OPTS -D params？

### ISSUE THREAD

**Issue by andotorg** [docker-library/tomcat#210]
i want use System.getProperty("evan.webapp") this param value，how setting  JAVA_OPTS -D param for start docker tomcat ？

**Comment by wglambert** [comment]
A few discussions with examples of ways you can use `JAVA_OPTS`

- With `-e` on `docker run` https://github.com/docker-library/tomcat/issues/189#issuecomment-594878531

- In a Dockerfile https://github.com/docker-library/tomcat/issues/8#issuecomment-149728019

- In a `docker-compose.yml` https://github.com/docker-library/tomcat/issues/8#issuecomment-242283842

**Comment by andotorg** [comment]
thanks for answer
