### ISSUE TITLE
Tomcat pipeline issue

### ISSUE THREAD

**Issue by jimenabarseghian** [docker-library/tomcat#213]
Hi,

Good morning. My team and I are trying to get the new version of  "tomcat:9.0.39-jdk8-adoptopenjdk-hotspot" that includes the "adoptopenjdk:8-jdk-hotspot" image that two days ago was updated to include Ubuntu 20.04 version. We noticed that the Jenkins pipeline is not working:

https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/tomcat/

This is the message:
WARNING: The Apache Tomcat Native library failed to load. The error reported was [tcnative-1 (Not found in java.library.path)]

Do you know when this issue could be fixed?

Thanks in advance, Jimena Barseghian (jimena.barseghian@aa.com)

**Comment by tianon** [comment]
Good catch, thanks!  Fixed in #214.
