### ISSUE TITLE
Corretto Alpine Support

### ISSUE THREAD

**Issue by jakauppila** [docker-library/tomcat#223]
The Amazon Corretto team offers alpine-based base images; would you take a PR to add these as another source?

https://hub.docker.com/_/amazoncorretto

**Comment by tianon** [comment]
Thanks for the suggestion!

Honestly our current support matrix is a bit out of control (which is admittedly mostly my fault for getting excited that we can without stopping to think whether we should), and IMO the cost still outweighs the value to be here given that Alpine isn't officially supported by the JDK ecosystem at large (see Project Portola for more details -- it might be more officially supported in version 16 or 17).

**Comment by jakauppila** [comment]
Just curious if there's any willingness for this yet?

**Comment by tianon** [comment]
Linking to the very relevant https://github.com/docker-library/tomcat/pull/248#issuecomment-1329908153 (sorry for not typing this up sooner :bow:).

**Comment by tianon** [comment]
Thanks for the push (and for the implementation suggestions!! :bow: :heart:); I'm going to close this now in order to consolidate into https://github.com/docker-library/tomcat/pull/299 :sweat_smile:
