### ISSUE TITLE
Corretto images use OpenSSL 1.0

### ISSUE THREAD

**Issue by veselov** [docker-library/tomcat#233]
It's a bummer that for Corretto, the native part is compiled against OpenSSL 1.0. That leaves quite a gaping hole in SSL support.

Can the native part be built against 1.1 instead?

**Comment by veselov** [comment]
@tianon Thank you for accepting the PR. Is it possible to push the updates images to Dockerhub, at least for latest versions?

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/10488 :+1:

(For posterity, this was fixed by https://github.com/docker-library/tomcat/pull/234)
