### ISSUE TITLE
Apopt OpenJDK deprecation 

### ISSUE THREAD

**Issue by frankholler** [docker-library/tomcat#237]
Please add new build for the replacement of Adopt OpenJDK,

"This image is officially deprecated in favor of the eclipse-temurin image, and will receive no further updates after 2021-08-01 (Aug 01, 2021). Please adjust your usage accordingly."

Source: https://hub.docker.com/_/adoptopenjdk

**Comment by tianon** [comment]
Unfortunately, https://hub.docker.com/_/eclipse-temurin/ doesn't have any JRE images, which is going to be a big blocking factor for using it more generally. :disappointed:
