### ISSUE TITLE
Provide openj9 (ibm-semeru-runtimes) based builds

### ISSUE THREAD

**Issue by smurfy** [docker-library/tomcat#247]
With the change of adopenjdk tomcat misses openj9 builds.

[ibm-semeru-runtimes](https://hub.docker.com/_/ibm-semeru-runtimes) provides openj9 versions, maybe it makes sense to use this as base for the builds.

**Comment by roded** [comment]
Any update on this issue? Is any help needed?

**Comment by tianon** [comment]
Linking to the very relevant https://github.com/docker-library/tomcat/pull/248#issuecomment-1329908153 (sorry for not typing this up sooner :bow:).

**Comment by tianon** [comment]
Thanks for the push (and for the implementation suggestions!! :bow: :heart:); I'm going to close this now in order to consolidate into https://github.com/docker-library/tomcat/pull/299 :sweat_smile:
