### ISSUE TITLE
Provide Sun Jre 7 & 8 Variants

### ISSUE THREAD

**Issue by cjnoyescrisp** [docker-library/tomcat#25]
We would prefer to use the sun runtime environment, sun are versions are available in then docker java repo. Is this possible?

**Comment by sylvainmouquet** [comment]
:+1: 
https://github.com/dockerfile/java/tree/master/oracle-java8

**Comment by macropin** [comment]
@tianon Now that you've moved to `openjdk` can we please have this, and also support legacy `FROM java`?

**Comment by yosifkit** [comment]
> Why is this only OpenJDK/OpenJRE?
>As all of the major upstream Linux distributions are unwilling to redistribute Oracle Java in their own distribution channels, we have chosen to follow them. See references below on how each distribution does not distribute Oracle Java.
>
> - Ubuntu stopped distributing it in the sun-java6 package when Oracle retired the "Operating System Distributor License for Java" (lists.ubuntu.com).
> - Debian requires users to download the Java tar manually from oracle.com and then use java-package to install it (wiki.debian.net).
> - The webupd8 PPA for Ubuntu and Debian requires the user to accept the Oracle license in order for their software to download and install Oracle java (webupd8.org).
> - Gentoo has a fetch-restriction that requires the user to go to the Oracle website to download the Java tar manually which inclues accepting the license (wiki.gentoo.org).
> - CentOS requires users to go and download the rpm provided by Oracle at java.com and thus accept the Oracle license (wiki.centos.org).
> - RedHat provides instructions to add a repo that is maintained by Oracle (access.redhat.com).
> 
>https://github.com/docker-library/docs/tree/399394aa5a1afa6f2b31ddb25ead54b3c6d1d244/java#why-is-this-only-openjdkopenjre

There is still legal uncertainty regarding distribution of Oracle Java so we await the day that Oracle provides a docker image (http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/).
