### ISSUE TITLE
Reliable way of knowing tomcat and jdk version

### ISSUE THREAD

**Issue by IvanNoronha-TomTom** [docker-library/tomcat#254]
I was using `tomcat:jdk11-openjdk-buster` for my war files and they stopped working suddenly when I redeployed(no code change and no update to Dockerfile).

swagger-ui would give the url issue
![image](https://user-images.githubusercontent.com/73875852/146740637-db68050b-a294-4f6b-88ee-0b49d5c53e4f.png)

After going through https://hub.docker.com/layers/tomcat/library/tomcat/jdk11-openjdk-buster/images/sha256-be5cf7ad5d4f85da69d3848316d31d21df4cea30ec888445a863d49bec3b8d27 I realised the tomcat version was 9.x.x couple of months back and now it is changed to10.x.x

So now I'm updating the base image to https://hub.docker.com/layers/tomcat/library/tomcat/9-jdk11-openjdk/images/sha256-8873fec970af3c70e315b43fd9366521d0c2a22004cb580ef602141f7da67988 because the tomcat version is 9.x.x

Is it fair to assume that the tomcat version(9.0.56) and openjdk version(11.0.13) will remain constant with `tomcat:9-jdk11-openjdk`? Or is it possible the version can also change?

Also how can one do a diff on the updates that are made to any tag?

**Comment by tianon** [comment]
The `9` in `tomcat:9-xxx` will always refer to Tomcat 9.x -- it might go from 9.0 to 9.5 (or whatever else constitutes a 9.x update in the future), but it will stay on the 9.x series.  Similarly, a tag containing `jdk11` will continue to contain version 11 of whatever Java runtime it contains.

We try to provide enough tags for each variant that you can choose as specific a "track" as you're willing to follow: https://github.com/docker-library/docs/blob/master/tomcat/README.md#supported-tags-and-respective-dockerfile-links (keeping in mind that some tags will be short-lived, like the tags for 10.1.0-M8 no longer receiving updates/rebuilds when 10.1.0-M9 or 10.1.0 GA are released).

If you want to see the history for a given tag, I'd suggest https://github.com/docker-library/repo-info/tree/master/repos/tomcat -- in your example of `jdk11-openjdk-buster`, I think this is probably the most useful place to look:

https://github.com/docker-library/repo-info/commits/master/repos/tomcat/remote/jdk11-openjdk-buster.md

(Admittedly, that's a bit easier to look at if you know the specific time period where the change occurred or if you know the specific change you're looking for, but in the latter case it's easier to browse from the command line with a local checkout instead.)
