### ISSUE TITLE
Use Tomcat Native 2

### ISSUE THREAD

**Issue by logopk** [docker-library/tomcat#278]
Would it be possible to provide a tomcat-native 2 image?

As far as I can tell this is just a replacement of the build from the packaged tar with the one provided as download. 

https://tomcat.apache.org/native-doc/

Thank you for looking into this!

**Comment by tianon** [comment]
The images we build include whatever version of Tomcat Native comes bundled with the relevant Tomcat version:

https://github.com/docker-library/tomcat/blob/72aa6d9977be017803205b071f2e227b1a6d3ec6/10.1/jdk17/temurin-jammy/Dockerfile#L82

If you look at the build output, you can see that number printed close to the end (and it should print during Tomcat startup, too):

Tomcat 10.1: https://github.com/docker-library/tomcat/actions/runs/3138672417/jobs/5098272244#step:5:1887

```console
INFO: Loaded Apache Tomcat Native library [2.0.1] using APR version [1.7.0].
```

Tomcat 10.0: https://github.com/docker-library/tomcat/actions/runs/3138672417/jobs/5098272471#step:5:2007

```console
INFO: Loaded Apache Tomcat Native library [1.2.35] using APR version [1.7.0].
```

So, if you need Tomcat Native 2.x, you want Tomcat 10.1+. :+1:
