### ISSUE TITLE
ppc64le/tomcat:latest exits with 132 RHEL

### ISSUE THREAD

**Issue by mtausk** [docker-library/tomcat#279]
72ed7d3f2c85  docker.io/ppc64le/tomcat:latest                catalina.sh run       34 seconds ago  Exited (132) 33 seconds ago                          inspiring_ptolemy

[root@mt-rhel85-01 ~]# uname -a
Linux mt-rhel85-01 4.18.0-348.el8.ppc64le #1 SMP Mon Oct 4 11:53:45 EDT 2021 ppc64le ppc64le ppc64le GNU/Linux
[root@mt-rhel85-01 ~]# cat /etc/*release*
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
Red Hat Enterprise Linux release 8.5 (Ootpa)
Red Hat Enterprise Linux release 8.5 (Ootpa)
cpe:/o:redhat:enterprise_linux:8::baseos

**Comment by tianon** [comment]
Exit code 132 is typically `SIGILL` - the `tomcat:latest` image is based on Ubuntu Jammy, which bumped the baseline for ppc64le from POWER8 to POWER9, and I'm guessing you're not on a POWER9 host?

**Comment by mtausk** [comment]
Correct. Thank you! Is this info missing in the doc or just I missed it?
We may close this one.

**Comment by yosifkit** [comment]
It is part of the Ubuntu Jammy release notes: https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668.

**Comment by yosifkit** [comment]
Any `-focal` versions will still work for power 8 machines. Tomcat `10.1` is not available on focal because Tomcat native requires openssl 3.
