### ISSUE TITLE
Add support for SAP Machine

### ISSUE THREAD

**Issue by ptrecenti** [docker-library/tomcat#281]
Hi I would like to add support for SAP Machine. #256

**Comment by tianon** [comment]
Linking to the very relevant https://github.com/docker-library/tomcat/pull/248#issuecomment-1329908153 (sorry for not typing this up sooner :bow:).

**Comment by tianon** [comment]
Thanks for the push (and for the implementation suggestions!! :bow: :heart:); I'm going to close this now in order to consolidate into https://github.com/docker-library/tomcat/pull/299 :sweat_smile:
