### ISSUE TITLE
tomcat 10.1 with corretto

### ISSUE THREAD

**Issue by logidru** [docker-library/tomcat#286]
Will there be a corretto version of Tomcat 10.1? as Version 10.0 reached EOL.

Regards Daniel

**Comment by tianon** [comment]
Tomcat 10.1 requires OpenSSL 3 (https://github.com/apache/tomcat-native/commit/f7930fa16f095717cfc641a8d24e60c343765adc) which Amazon Linux 2 does not (to my knowledge) include.

I think https://github.com/docker-library/tomcat/pull/248#issuecomment-1329908153 is also very, very relevant.

**Comment by logidru** [comment]
ah got it, amzonlinux 2 does not support, but amatonlinux 2022 does. But did you already decide to kick out all images out instead of jammy? or are you still supporting amazoncorretto:17-al2022-jdk as soon this is officially released (currently tagged as RC)

**Comment by tianon** [comment]
We didn't kick out AL2 variants yet, but we haven't prioritized "fixing" anything about them (like this issue) thanks to that overarching discussion/quandary.

**Comment by veselov** [comment]
FWIW, https://github.com/docker-library/tomcat/pull/298
Some of the changes are shady, since al2023 switched to DNF.

**Comment by tianon** [comment]
Thanks for the push (and for the implementation suggestions!! :bow: :heart:); I'm going to close this now in order to consolidate into https://github.com/docker-library/tomcat/pull/299 :sweat_smile:
