### ISSUE TITLE
Create new image 9.0.71-jdk11-openjdk

### ISSUE THREAD

**Issue by ivanrome** [docker-library/tomcat#287]
Hello,

Could you generate a image for the latest version of tomcat 9.0.71, with openjdk11?

Regards

**Comment by yosifkit** [comment]
The bot has already picked up the change for the Dockerfiles: https://github.com/docker-library/tomcat/commit/2fe063250eb12b5a1a49e91dbb8e69f4a4127e45

The rest of the steps for it to appear on Docker Hub are linked in the readme: https://github.com/docker-library/tomcat/tree/2fe063250eb12b5a1a49e91dbb8e69f4a4127e45#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
