### ISSUE TITLE
Java19

### ISSUE THREAD

**Issue by oeresundsgruppen** [docker-library/tomcat#292]
Hi, how about java19 upgrade ?

**Comment by wglambert** [comment]
See https://github.com/docker-library/tomcat/issues/258#issuecomment-1329909183 and https://github.com/docker-library/tomcat/pull/275#issuecomment-1235938409
>we do not plan on basing the tomcat images on any non-LTS version of the JDk.
>https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by oeresundsgruppen** [comment]
you dont have to make more images, just add multiple versions to each and support parsing in variable to set version...

**Comment by tianon** [comment]
Is passing in a variable really much different from making the slight modification to the `Dockerfile` yourself?  (another approach could be to use `--build-context` on `docker buildx build` to swap the base image we're using out for a different one during build)

Unfortunately, doing _more_ here is not something we're willing to maintain.
