### ISSUE TITLE
Unrecognized VM option 'UseConcMarkSweepGC' with tomcat:9-jre17

### ISSUE THREAD

**Issue by spawn-guy** [docker-library/tomcat#307]
i am running `oscarfonts/docker-geoserver` on AWS ElasticBeanstalk `Docker running on 64bit Amazon Linux 2/3.5.9` 

with the images based on `tomcat:9-jdk11` i don't have any problems, but with later images based on `tomcat:9-jre17` i do receive an error
```
stdout: , stderr: NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Can someone help solving this?

is this `tomcat-docker` or `docker-geoserver` or `AWS` issue?
posted here as well https://github.com/oscarfonts/docker-geoserver/issues/42

**Comment by tianon** [comment]
We do not set that option anywhere in our image, so likely `geoserver` :see_no_evil:
