### ISSUE TITLE
GraalVM

### ISSUE THREAD

**Issue by oeresundsgruppen** [docker-library/tomcat#309]
Hi, Any plans of Tomcat with GraalVM 21 ?

**Comment by yosifkit** [comment]
There are no plans to add graalvm variants (this would be the same as https://github.com/docker-library/tomcat/pull/299). But also, there isn't a graalvm Docker Official Image to base it on as the upstream was not interested (https://github.com/docker-library/official-images/pull/10936 and https://github.com/graalvm/container/issues/22).

**Comment by oeresundsgruppen** [comment]
Sad, there are some serious optimizations in graalvm, can blow performance at times
