### ISSUE TITLE
Unable to install Tomcat 9 - **"Package 'tomcat9' has no installation candidate"** || Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by dipualnur** [docker-library/tomcat#313]
I'm trying to install Tomcat 9 on my Ubuntu system using `*

`sudo apt-get install tomcat9
`
but I keep running into the following error:

```
monirul@nitacl-Veriton-Series:~$ sudo apt-get install tomcat9 
Reading package lists... 
Done 
Building dependency tree... 
Done 
Reading state information... 
Done 
Package tomcat9 is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source E: Package 'tomcat9' has no installation candidate
```

Here's what I've tried so far:

```
sudo apt update Searching for alternative package names (e.g., tomcat9.0, tomcat-9) using apt-cache search tomcat
```

System Information: Ubuntu version: 24.04 LTS Noble Numbat
Architecture: LAMP

Could anyone please point me in the right direction? Is there a specific repository I need to enable or a different approach to installing Tomcat 9?

Thanks in advance for your help!****

**Comment by LaurentGoderre** [comment]
This repo is for the Docker image for tomcat so this would be out of scope but my guess is that there are no pre-built packages in that OS for the architecture you are in.
