### ISSUE TITLE
JDK 22 support

### ISSUE THREAD

**Issue by sergey-morenets** [docker-library/tomcat#315]
Hi

Do you have any plans supporting JDK 22 as base image?
I looked at the repository tags here: https://hub.docker.com/_/tomcat and saw only JDK 21 or JRE 21 as base image (for both 10.1.x and 11.x versions) ?
It doesn't allow us to fully migrate our projects to JDK 22.

**Comment by tianon** [comment]
Unfortunately, we currently only support LTS Java versions; see https://github.com/docker-library/tomcat/pull/299 for more details/discussion.
