### ISSUE TITLE
fix version tomcat:9.0.95-jre11 causes angular to break when run in chromium using taiko gauge testing framework

### ISSUE THREAD

**Issue by mbradleySoftrams** [docker-library/tomcat#322]
We recently started seeing failures in our testing framework when run our smoke testing pipelines. 
The angular version being used is 17.3.1 and the error we get when testing using the latest chromuim headless browser is a failure to load the js files for Pollyfill.js and other js libraries.

**Comment by LaurentGoderre** [comment]
This sounds like an issue with the content being hosted using tomcat and not tomcat itself

**Comment by mbradleySoftrams** [comment]
Thanks for replying. It is a very odd issue with how the container env variables were configured.
