### ISSUE TITLE
GPG_KEY获取的网站失效

### ISSUE THREAD

**Issue by zhouyibetter** [docker-library/tomcat#324]
ha.pool.sks-keyservers.net换成keyserver.ubuntu.com

**Comment by yosifkit** [comment]
`sks-keyservers.net` has not been used in a while; `keyserver.ubuntu.com` is the current server used: https://github.com/docker-library/tomcat/blob/3473b76f4f050aff1529e0a585894b2140adc5a7/Dockerfile.template#L118
