### ISSUE TITLE
CATALINA_PID file is not created

### ISSUE THREAD

**Issue by dpeger** [docker-library/tomcat#41]
I'm encountering the problem that the process ID file, that can be specified by the `CATALINA_PID` variable, is not created on tomcat start.

Basically I created a Dockerfile based on `tomcat:7`:
```
FROM tomcat:7
ENV CATALINA_PID "${CATALINA_HOME}/bin/catalina.pid"
```

If I start this image it's correctly printing the expected environment values:
```
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-7-openjdk-amd64/jre
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Using CATALINA_PID:    /usr/local/tomcat/bin/catalina.pid
```

But when I inspect the instance by executing bash in the container, there is no PID file...

```
$ docker exec -it 69d8006ba49f bash
root@69d8006ba49f:/usr/local/tomcat# cd bin/
root@69d8006ba49f:/usr/local/tomcat/bin# ls -la
total 372
drwxr-xr-x  2 root root    4096 Aug 11 20:39 .
drwxr-sr-x 14 root staff   4096 Aug 19 11:42 ..
-rw-r--r--  1 root root   27099 Jun 15 16:40 bootstrap.jar
-rw-r--r--  1 root root    1647 Jun 15 16:41 catalina-tasks.xml
-rwxr-xr-x  1 root root   21646 Jun 15 16:40 catalina.sh
-rw-r--r--  1 root root  204944 Jun 15 16:40 commons-daemon-native.tar.gz
-rw-r--r--  1 root root   24283 Jun 15 16:40 commons-daemon.jar
-rwxr-xr-x  1 root root    1922 Jun 15 16:40 configtest.sh
-rwxr-xr-x  1 root root    7888 Jun 15 16:40 daemon.sh
-rwxr-xr-x  1 root root    1965 Jun 15 16:40 digest.sh
-rwxr-xr-x  1 root root    3547 Jun 15 16:40 setclasspath.sh
-rwxr-xr-x  1 root root    1902 Jun 15 16:40 shutdown.sh
-rwxr-xr-x  1 root root    1904 Jun 15 16:40 startup.sh
-rw-r--r--  1 root root   38197 Jun 15 16:40 tomcat-juli.jar
-rwxr-xr-x  1 root root    5024 Jun 15 16:40 tool-wrapper.sh
-rwxr-xr-x  1 root root    1908 Jun 15 16:40 version.sh
root@69d8006ba49f:/usr/local/tomcat/bin# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ssl+   0:03 /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -Djava.util.logging.config.file=/usr/local/tom...
   20 ?        Ss     0:00 bash
   33 ?        R+     0:00 ps ax
root@69d8006ba49f:/usr/local/tomcat/bin#
```

Is there an additional option that must be set to make tomcat generate the PID file?

The above Dockerfile is only a MCVE. In the real container I start tomcat by some wrapper scripts and need to shut it down on exit of the script. That is why I'm in need of the PID file...

**Comment by yosifkit** [comment]
The pid file is only used on `catalina.sh start`, which won't work for the regular docker container since we need the process to stay in the foreground and not fork, but should work for your scripts.

```console
$ cat bin/catalina.sh
...
#   CATALINA_PID    (Optional) Path of the file which should contains the pid
#                   of the catalina startup java process, when start (fork) is
#                   used
```

```bash
# I am guessing that you are currently doing something like this:
catalina.sh run &

# where this should work better, as long as you have the PID file envvar
catalina.sh start

# then you can use this to stop it
catalina.sh stop
# though if the end of your script is the end of the container 
# it would just kill the catalina process when the container stops anyway.
```

**Comment by dpeger** [comment]
Actually I need to use `catalina.sh run` as I need to attach my script to the started tomcat process after some additional steps as this is the main process for the docker container.

As I have the process ID at hand after starting tomcat, I think I'll create the PID file myself to be able to stop tomcat gracefully on docker stop.

I'm wondering what the desired shutdown behaviour of the tomcat container would be. If I stop a default `tomcat:7` container by issuing `docker stop <container-id>` the container exits with exit code 143. If I issue a `catalina.sh stop` on the container, exit code is 0.

**Comment by ohtaro** [comment]
@dpeger 
try docker stop --signal=SIGINT <container-name or id>

**Comment by bqdevops** [comment]
Following your advice @yosifkit , I'm doing this in my script inside the container:

```bash
# Trap the SIGTERM so we can exit cleanly
trap 'catalina.sh stop; exit 0' SIGTERM

# Start Tomcat
catalina.sh start

# Show output of Tomcat startup
tail -f logs/catalina.out &

## A bunch of work after the tomcat-hosted application comes online
<snip>

# Hang around until we get the SIGTERM
tail -f /dev/null & wait
```

This seems to be a solid technique for cleanly exiting Tomcat when docker sends its STOPSIGNAL to my pid 1 script, but `catalina.sh` never writes the pid file—it will `rm` the pid file but it never creates it for some reason and I'm not sure why.

**Comment by RulerOf** [comment]
Following your advice @yosifkit , I'm doing this in my script inside the container:

```bash
# Trap the SIGTERM so we can exit cleanly
trap 'catalina.sh stop; exit 0' SIGTERM

# Start Tomcat
catalina.sh start

# Show output of Tomcat startup
tail -f logs/catalina.out &

## A bunch of work after the tomcat-hosted application comes online
<snip>

# Hang around until we get the SIGTERM
tail -f /dev/null & wait
```

This seems to be a solid technique for cleanly exiting Tomcat when docker sends its STOPSIGNAL to my pid 1 script, but `catalina.sh` never writes the pid file—it will `rm` the pid file but it never creates it for some reason and I'm not sure why.
