### ISSUE TITLE
chown operation not permitted when running container with new user

### ISSUE THREAD

**Issue by shaileshpandey11** [docker-library/tomcat#43]
Command in DockerFile:
RUN chown -R tms /usr/local/tomcat/webapps/webservices-0.0.1-20160824.053225-11.war

Log:
Step 13 : RUN chown -R tms /usr/local/tomcat/webapps/webservices-0.0.1-20160824.053225-11.war
 ---> Running in 9855537059c2
chown: changing ownership of ‘/usr/local/tomcat/webapps/webservices-0.0.1-20160824.053225-11.war’: Operation not permitted

**Comment by yosifkit** [comment]
What does the rest of your Dockerfile look like?  If you have a `USER` line previously that is not root, then that user probably won't have permission to chown the file.

**Comment by shaileshpandey11** [comment]
Thanks @yosifkit  i was doing wrong after creating USER previously. I have changed that and now it's working.
