### ISSUE TITLE
The Tomcat 8.0.36 image needs to change to 8.0.37. 

### ISSUE THREAD

**Issue by sdouglasnelson** [docker-library/tomcat#45]
8.0.36 is no longer accessible at https://www.apache.org/dist/tomcat/tomcat-8/

**Comment by tianon** [comment]
See https://github.com/docker-library/tomcat/commit/6b46a2812e6a8ad528a8004fa16ea66cc48b1420 and https://github.com/docker-library/official-images/pull/2122. :+1:
