### ISSUE TITLE
Support for SSL certificates in keystore

### ISSUE THREAD

**Issue by edwardotis** [docker-library/tomcat#50]
Feature Request:
This docker image has added instructions and support for using your own ssl certificates in a Tomcat image.

https://hub.docker.com/r/chrisipa/tomcat/
https://hub.docker.com/r/chrisipa/tomcat/~/dockerfile/

I think it would be very beneficial for the official tomcat library to include support for SSL/TLS certificates as well.

**Comment by tianon** [comment]
Sorry for the really long tail here :disappointed:

We definitely "support" TLS certificates here, as much as Tomcat itself does.  The downside is that we require you to configure Tomcat to use them appropriately yourself.  Unfortunately, Tomcat's configuration is XML-based, so doing automated changes to it is more complicated than it really should be, and we try to provide a "vanilla" Tomcat experience as much as possible.
