### ISSUE TITLE
open ssl not found can't build tomcat

### ISSUE THREAD

**Issue by SelvaSurukam** [docker-library/tomcat#54]
while docker-compose build

> `E: Version '1.0.2h-1' for 'openssl' was not found
> ERROR: Service 'tomcat' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends           libapr1                 openssl="$OPENSSL_VERSION"      && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100`

![image](https://cloud.githubusercontent.com/assets/14159289/20028174/78f5f70e-a350-11e6-968d-27b4c3203c7e.png)

**Comment by Skiamakhos** [comment]
Try 1.0.1t-1+deb8u5 - this seems to work to an extent, BUT it will still fall over later with a dependency error caused by an incompatibility between the JRE & JDK version numbers.

**Comment by yosifkit** [comment]
It looks like you are building from an older Dockerfile; the current version is [`1.0.2j-1`](https://github.com/docker-library/tomcat/blob/f26c14147f9affae8f32100430130271fc82bd3e/Dockerfile.template#L15).  Is there a particular reason you are building them, rather than just doing a `docker pull`?

**Comment by Skiamakhos** [comment]
1.0.2j-1 gives the same results tbh.

**Comment by tianon** [comment]
See also https://github.com/docker-library/tomcat/pull/56

**Comment by rossbachp** [comment]
If I use "ENV OPENSSL_VERSION 1.1.0c-2" it works.

**Comment by yosifkit** [comment]
This is related to https://github.com/docker-library/postgres/issues/228.  We want to ensure our images build the correct version or fail; since the openssl version is important to build tomcat, we want to also ensure that it gets properly pinned from the stretch repo.  Our update script is made to bump this version when it can.
