### ISSUE TITLE
can't debug tomcat - missing JDK

### ISSUE THREAD

**Issue by damovsky** [docker-library/tomcat#55]
Hi there,
I can't run tomcat in debug mode...it seems the whole image contains only JRE,but JDK is required to run tomcat in debug mode...

I can start the tomcat....
```
$ docker run -it tomcat:8.5.6-jre8 catalina.sh start
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-8-openjdk-amd64/jre
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Tomcat started.
```
...but can't debug it
```
$ docker run -it tomcat:8.5.6-jre8 catalina.sh debug
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

I wonder if this is a known issue and if there is any workaround....am I the only one who uses tomcat in debug mode?

**Comment by rodrigofalco** [comment]
For anyone facing this issue.
Extending from this image, you could install openjdk.
We used run as the CMD as with start jdpa and debug the container was being killed as soon as it started.

Here, Is how we did it.

There is a setenv.sh file with this content
`
JAVA_OPTS="$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000"
`

And then, our dockerfile 


```
FROM tomcat:8.5.8
MAINTAINER Rodrigo Falco <rodrigo@patagonian.it>

RUN apt-get update && \
apt-get install -y git build-essential curl wget software-properties-common

RUN echo deb http://http.debian.net/debian jessie-backports main >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y openjdk-8-jdk
RUN update-alternatives --config java

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

COPY setenv.sh /usr/local/tomcat/bin/

EXPOSE 8000

CMD ["catalina.sh", "run"]

```

**Comment by bjoerndev** [comment]
Perhaps even easier: 
Using "FROM tomcat:8.5.15-jre8" which itself uses "FROM openjdk:8-jre" [1], I only had to set CATALINA_OPTS to activate tomcat debugging:
```
ENV CATALINA_OPTS "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000"
EXPOSE 8000
```

[1] https://github.com/docker-library/tomcat/blob/5ac222d258dc70c77bb3a9a4fab81ea286c9abd1/8.5/jre8/Dockerfile

**Comment by tianon** [comment]
Nice, closing given the excellent and simple solution using `CATALINA_OPTS` provided above. :+1:

(Which should be trivial to provide either via `Dockerfile` or via `-e` on the `docker run` command line.)

**Comment by abrotons** [comment]
Just a note. From Java 9 onwards, JDWP address needs to be set as `host:port`, instead of just the `port`.

So if you upgrade to any `-jre10` Tomcat, you will need to use:
```
ENV CATALINA_OPTS "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
EXPOSE 8000
```
