### ISSUE TITLE
Use `ARG` instead of `ENV`?

### ISSUE THREAD

**Issue by chenrui333** [docker-library/tomcat#60]
For some build-time variables, it would be good to use just `ARG` instead of `ENV`. 

> Unlike an ARG instruction, ENV values are always persisted in the built image.

For example, the variables like `TOMCAT_MAJOR`, `TOMCAT_VERSION`, `TOMCAT_TGZ_URL`, `TOMCAT_ASC_URL`. 

Just a thought!

**Comment by tianon** [comment]
Are these variables causing problems somewhere?  IMO switching to "ARG"
implies that they're supposed to be user-serviceable via "--build-arg",
which really isn't the case here.

**Comment by chenrui333** [comment]
It did not cause any problem, but just feel like `ARG` would be more appropriate.

**Comment by yosifkit** [comment]
`ARG` is not great unless necessary, especially given that it makes the output of docker history unnecessarily difficult to parse for both for humans and for computers.

Related: https://github.com/docker-library/php/issues/698
