### ISSUE TITLE
E: Version '1.0.2c-2' for 'openssl' was not found

### ISSUE THREAD

**Issue by sohailravian** [docker-library/tomcat#72]
E: Version '1.0.2c-2' for 'openssl' was not found
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends            libapr1                 openssl="$OPENSSL_VERSION"      && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

I am trying to build docker file for tomcat 7 from docker hub and i am getting this exception. I am unable to resolve it. Please tell me what is wrong?

**Comment by yosifkit** [comment]
I don't see `1.0.2-c` anywhere in our history (`git log -p | grep '1.0.2c'`), so I am not sure where that value came from.  The current value is `ENV OPENSSL_VERSION 1.1.0e-2`, which was added to the Dockerfiles over the weekend (was `1.1.0e-1`).  Have you pulled master recently or have some local changes?  The other related question is why are you building when you could just `docker pull tomcat:7`?
