### ISSUE TITLE
How to set JVM parameters?

### ISSUE THREAD

**Issue by kdekooter** [docker-library/tomcat#8]

**Comment by md5** [comment]
You can pass `JAVA_OPTS` to the JVM like so:

    docker run --rm -e JAVA_OPTS='-Xmx1g' tomcat

**Comment by pperez** [comment]
Is there a way to use another environment variable inside JAVA_OPTS? I want to use the $CATALINA_HOME for storing logs

**Comment by yosifkit** [comment]
Something like `docker run ... tomcat sh -c 'export JAVA_OPTS="$JAVA_OPTS --logargs=$CATALINA_HOME/logs"; exec catalina.sh run'`?

**Comment by md5** [comment]
In a derived image, something like this should work:

```Dockerfile
FROM tomcat
ENV JAVA_OPTS="-Dmy.log.path=$CATALINA_HOME/path/to/logs"
```

You'll have to take care if `-e JAVA_OPTS` is used as well, though. In that case, you'd have to do something like what @yosifkit recommended to combine the image-defined `JAVA_OPTS` with your additional opts.

**Comment by md5** [comment]
To be more clear, you can't use `-e JAVA_OPTS="$OTHER_OPTS"` without losing the options defined by `ENV JAVA_OPTS="..."` in your derived imag.

**Comment by pperez** [comment]
Thanks!

**Comment by mictadlo** [comment]
I am using a Dockerfile which is based on `tomcat:7` and I would like to increase the memory for tomcat. I inserted in this  in the following [docker-compose.yml](https://github.com/GMOD/docker-apollo/blob/master/docker-compose.yml) file:

    environment:
      CATALINA_OPTS: "-Xmx12288m -Xms8192m \
        -XX:PermSize=256m \
        -XX:MaxPermSize=1024m \
        -XX:ReservedCodeCacheSize=64m \
        -XX:+UseG1GC \
        -XX:+CMSClassUnloadingEnabled \
        -XX:+PrintHeapAtGC \
        -XX:+PrintGCDetails \
        -XX:+PrintGCTimeStamps"

Is it correct or how can I check it?

Thank you in advance.

Mic

**Comment by kelvinklein** [comment]
@mictadlo 

your environment settings for CATALINA_OPTS did this work?

**Comment by juliangamble** [comment]
Note that for the CATALINA_OPTS - you'll need to strip out the double-quotes.

**Comment by mictadlo** [comment]
Thank you.

**Comment by yosifkit** [comment]
Closing old issue. Looks like this was solved.

**Comment by clement-igonet** [comment]
And so, could you write your final working solution for splitting your CATALINA_OPTS var in several lines?
