### ISSUE TITLE
 tomcat:8.0-jre8 throws java.awt.AWTError

### ISSUE THREAD

**Issue by mlechner** [docker-library/tomcat#80]
The most recent tomcat:8.0-jre8 image (sha256:ee79d209fabf4fb03fc9436360d9dcceac6bc31d1dd93ff5c45d62aded85edc1) throws a  java.awt.AWTError similar to https://askubuntu.com/questions/695560/assistive-technology-not-found-error-while-building-aprof-plot
openjdk-8-jre-headless does not work together with assistive_technologies=org.GNOME.Accessibility.AtkWrapper set in /etc/java-8-openjdk/accessibility.properties
Fix might be to deactivate assistive_technologies entry or to use openjdk-8-jre instead of -headless

**Comment by mlechner** [comment]
image used is sha256:b9e1cd81650aeb837a53acbaf1a8a1a627f329d8c6030f8b7b1fc8e4a9444eed
instead of the one above.

**Comment by agois-inc** [comment]
When building docker you can remove the offending file:

```
rm /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/accessibility.properties
rm /etc/java-8-openjdk/accessibility.properties
```

**Comment by mjji** [comment]
got the same problem here. Disabling the setting solved it. Should be disabled by default.

**Comment by mlechner** [comment]
I wonder why this is not solved by the maintainer yet? What else is needed?

**Comment by tianon** [comment]
This would be a bug in the upstream `openjdk-8-jre` package of Debian.

Also, the note in the OP about not using the headless package no longer applies, because this image contains the full JRE:

```console
$ docker run --rm tomcat:8.0-jre8 dpkg -l | grep openjdk
ii  openjdk-8-jre:amd64           8u151-b12-1~deb9u1             amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64  8u151-b12-1~deb9u1             amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```

**Comment by mlechner** [comment]
Then this issue could be closed, right?

**Comment by yosifkit** [comment]
As far as I can tell it can be closed. Feel free to comment if the current image using the full jre still fails.
