### ISSUE TITLE
Tomcat link oracle database problem(Solved)

### ISSUE THREAD

**Issue by dragonbest520** [docker-library/tomcat#83]
I deployed a springmvc program in tomcat(docker) and link the container to a oracle docker container. There is a java exception like this:

`Caused by: java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01882: timezone region  not found`

I search on Google and find the solution: 
Change the  content of file /etc/timezone in your tomcat docker container to 
`CST`
And restart tomcat container. 
Problem solved.

You can also add /etc/timezone file in Dockerfile and rebuild tomcat image.

**Comment by tianon** [comment]
Since this doesn't look like an issue with the image, I'm going to close it, but hopefully this additional information will help others searching in the future!

You might also be able to simply set the `TZ` environment variable to an appropriate string, such as `-e TZ=CST`. :+1:
