### ISSUE TITLE
collect access.log to docker log driver

### ISSUE THREAD

**Issue by 1026524749** [docker-library/tomcat#84]
Tomcat catalina.log is collected to stdout，but access.log is output to file in the container。
How do I to collect access.log by docker log driver？

**Comment by tianon** [comment]
I think the following section in the default `conf/server.xml` is probably relevant:
```xml
        <!-- Access log processes all example.
             Documentation at: /docs/config/valve.html
             Note: The pattern used is equivalent to using pattern="common" -->
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />
```

If all else fails, you could create a short `Dockerfile` that's `FROM tomcat:X.Y` which creates a symlink from the access log file to `/dev/stdout` (like NGINX does: https://github.com/nginxinc/docker-nginx/blob/48a4c531fc4bfa80d4270f20a67e2e958856860c/stable/stretch/Dockerfile#L91-L93).

**Comment by srossross** [comment]
I've modified my conf/server.xml, this works for me:

```
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="/proc/self/fd"
               prefix="1" suffix="" rotatable="false"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />
```

**Comment by tianon** [comment]
Nice, thanks for confirming @srossross! :+1:

**Comment by connachtguy** [comment]
> I've modified my conf/server.xml, this works for me:
> 
> ```
>         <Valve className="org.apache.catalina.valves.AccessLogValve" directory="/proc/self/fd"
>                prefix="1" suffix="" rotatable="false"
>                pattern="%h %l %u %t &quot;%r&quot; %s %b" />
> ```

I have a containerized app that spews it's log messages to standard out. It runs on tomcat, and we created a symbolic link from the tomcat access log to /dev/stdout which seemed to work, but we found that occasionally the application messages were clashing with the access log messages. I'm wondering if there's any reason to think this /proc/self/fd approach would be any better?

**Comment by arulrajnet** [comment]
```
<Valve className="org.apache.catalina.valves.AccessLogValve" 
            directory="/dev" prefix="stdout" suffix="" pattern="%h %l %u %t &quot;%r&quot; %s %b" 
            buffered="false" fileDateFormat=""/>
```

This sends the accesslog into stdout.

**Comment by sujiansoft** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
