### ISSUE TITLE
Add alternate keyserver mirrors for gpg keys

### ISSUE THREAD

**Issue by Jaskaranbir** [docker-library/tomcat#87]
From what I have observed, `ha.pool.sks-keyservers.net` is not very reliable and I have failed to receive keys on several occasions.

I think we should add alternative mirrors, something like:

```
RUN set -ex; \
	for key in $GPG_KEYS; do \
    gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
    gpg --keyserver keyserver.pgp.com --recv-keys "$key" || \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ; \
	done
```

**Comment by tianon** [comment]
Indeed, this would be a very welcome addition!

It'd probably be a good idea to also include some port-80 based servers like `hkp://p80.pool.sks-keyservers.net:80` and `hkp://keyserver.ubuntu.com:80` for folks behind firewalls.

My own preferred ordering would be the following:

- `ha.pool.sks-keyservers.net`
- `pgp.mit.edu`
- `hkp://p80.pool.sks-keyservers.net:80`
- `hkp://keyserver.ubuntu.com:80`
- `keyserver.pgp.com`

**Comment by marcvanandel** [comment]
I've stumbled upon this issue of some other project not related to this but with a proposal for the keyserver issue as well: https://github.com/tianon/gosu/issues/35

Replacing line
`gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \`

with 
```
        for server in $(shuf -e ha.pool.sks-keyservers.net \
                                hkp://p80.pool.sks-keyservers.net:80 \
                                keyserver.ubuntu.com \
                                hkp://keyserver.ubuntu.com:80 \
                                keyserver.pgp.com \
                                pgp.mit.edu) ; do \
            gpg --keyserver "$server" --recv-keys $key && break || : ; \
        done; \
```
seems to work just fine (locally 'on my machine' ;-)

**Comment by yosifkit** [comment]
Closing since it is not something we are interested in adding to our images: https://github.com/docker-library/tomcat/pull/108#issuecomment-363510873.

**Comment by tanzeelrana** [comment]
I wrote this from reading the information in all the comments above. Does this look good ?

```
RUN set -ex \
  && for key in \
    4ED778F539E3634C779C87C6D7062848A1AB005C \
    B9E2F5981AA6E0CD28160D9FF13993A75599653C \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    77984A986EBC2AA786BC0F66B01FBB92821C587A \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
    56730D5401028683275BD23C23EFEFE93C4CFFFE \
  ; do \
    for server in $( \
      shuf -e ha.pool.sks-keyservers.net \
      hkp://p80.pool.sks-keyservers.net:80 \
      keyserver.ubuntu.com \
      hkp://keyserver.ubuntu.com:80 \
      keyserver.pgp.com \
      pgp.mit.edu \
    ) ; do \
      gpg --keyserver "$server" --recv-keys "$key" && break || : ; \
    done; \
  done
```
