### ISSUE TITLE
tomcat:8.0-jdk8 is not available 

### ISSUE THREAD

**Issue by BruceZu** [docker-library/tomcat#98]
Sorry, This is not an issue. Just a question. 
May I know if there would be tomcat:8.0-jdk8 
Currently, we only have tomcat:8.0-jre8.  based on it I cannot create customized docker image to let 
``` bash 
 mvn package
``` 
work.  `mvn package` will call javac

**Comment by tianon** [comment]
See also https://github.com/docker-library/tomcat/issues/55 and https://github.com/docker-library/tomcat/pull/89 (one of which this is arguably a duplicate of).

**Comment by BruceZu** [comment]
Thank you so much 
I add 
```yml
apt-get install -y \
    openjdk-8-jdk="$JAVA_DEBIAN_VERSION" \
    ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION"
```
to make sure the jdk version is same as the existing jre.
