### ISSUE TITLE
Tomcat Access logs are not getting forwarded to Fleuntd LogDriver

### ISSUE THREAD

**Issue by Thanikassalam** [docker-library/tomcat#99]
When redirecting tomcat logs to fluentd host, i'm not getting tomcat access logs, rest all logs are coming.
However they are getting stored in logs/localhost_access_log.txt as per conf/server.xml configurations.
Is there any way we can forward the access logs to stdout so that it will be forwarded to fluentd logdriver ?

**Comment by tianon** [comment]
See https://github.com/docker-library/tomcat/issues/84. :wink:
